// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.1
// Source: auths.proto

package authsclient

import (
	"context"

	"github.com/falconfan123/Go-mall/services/auths/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AuthGenReq     = pb.AuthGenReq
	AuthGenRes     = pb.AuthGenRes
	AuthRenewalReq = pb.AuthRenewalReq
	AuthRenewalRes = pb.AuthRenewalRes
	AuthReq        = pb.AuthReq
	AuthValidateReq = pb.AuthValidateReq
	AuthValidateRes = pb.AuthValidateRes
	AuthsRes       = pb.AuthsRes
	LogoutReq       = pb.LogoutReq
	LogoutRes       = pb.LogoutRes

	Auths interface {
		// Authentication 验证用户token合法
		Authentication(ctx context.Context, in *AuthReq, opts ...grpc.CallOption) (*AuthsRes, error)
		// GenerateToken 生成token
		GenerateToken(ctx context.Context, in *AuthGenReq, opts ...grpc.CallOption) (*AuthGenRes, error)
		// RenewToken 续期身份
		RenewToken(ctx context.Context, in *AuthRenewalReq, opts ...grpc.CallOption) (*AuthRenewalRes, error)
		// ValidateToken 验证长短令牌（用于网关）
		ValidateToken(ctx context.Context, in *AuthValidateReq, opts ...grpc.CallOption) (*AuthValidateRes, error)
		// Logout 登出（删除Session）
		Logout(ctx context.Context, in *LogoutReq, opts ...grpc.CallOption) (*LogoutRes, error)
	}

	defaultAuths struct {
		cli zrpc.Client
	}
)

func NewAuths(cli zrpc.Client) Auths {
	return &defaultAuths{
		cli: cli,
	}
}

// Authentication 验证用户token合法
func (m *defaultAuths) Authentication(ctx context.Context, in *AuthReq, opts ...grpc.CallOption) (*AuthsRes, error) {
	client := pb.NewAuthsClient(m.cli.Conn())
	return client.Authentication(ctx, in, opts...)
}

// GenerateToken 生成token
func (m *defaultAuths) GenerateToken(ctx context.Context, in *AuthGenReq, opts ...grpc.CallOption) (*AuthGenRes, error) {
	client := pb.NewAuthsClient(m.cli.Conn())
	return client.GenerateToken(ctx, in, opts...)
}

// RenewToken 续期身份
func (m *defaultAuths) RenewToken(ctx context.Context, in *AuthRenewalReq, opts ...grpc.CallOption) (*AuthRenewalRes, error) {
	client := pb.NewAuthsClient(m.cli.Conn())
	return client.RenewToken(ctx, in, opts...)
}

// ValidateToken 验证长短令牌（用于网关）
func (m *defaultAuths) ValidateToken(ctx context.Context, in *AuthValidateReq, opts ...grpc.CallOption) (*AuthValidateRes, error) {
	client := pb.NewAuthsClient(m.cli.Conn())
	return client.ValidateToken(ctx, in, opts...)
}

// Logout 登出（删除Session）
func (m *defaultAuths) Logout(ctx context.Context, in *LogoutReq, opts ...grpc.CallOption) (*LogoutRes, error) {
	client := pb.NewAuthsClient(m.cli.Conn())
	return client.Logout(ctx, in, opts...)
}
