// Code generated by MockGen. DO NOT EDIT.
// Source: services/users/internal/application/event/event_publisher.go
//
// Generated by this command:
//
//	mockgen -source services/users/internal/application/event/event_publisher.go -package testmock -destination services/users/internal/testmock/mock_event_publisher.go
//

// Package testmock is a generated GoMock package.
package testmock

import (
	reflect "reflect"

	event "github.com/falconfan123/Go-mall/services/users/internal/domain/event"
	gomock "go.uber.org/mock/gomock"
)

// MockEventPublisher is a mock of EventPublisher interface.
type MockEventPublisher struct {
	ctrl     *gomock.Controller
	recorder *MockEventPublisherMockRecorder
	isgomock struct{}
}

// MockEventPublisherMockRecorder is the mock recorder for MockEventPublisher.
type MockEventPublisherMockRecorder struct {
	mock *MockEventPublisher
}

// NewMockEventPublisher creates a new mock instance.
func NewMockEventPublisher(ctrl *gomock.Controller) *MockEventPublisher {
	mock := &MockEventPublisher{ctrl: ctrl}
	mock.recorder = &MockEventPublisherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventPublisher) EXPECT() *MockEventPublisherMockRecorder {
	return m.recorder
}

// PublishAddressAdded mocks base method.
func (m *MockEventPublisher) PublishAddressAdded(e *event.AddressAddedEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishAddressAdded", e)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishAddressAdded indicates an expected call of PublishAddressAdded.
func (mr *MockEventPublisherMockRecorder) PublishAddressAdded(e any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishAddressAdded", reflect.TypeOf((*MockEventPublisher)(nil).PublishAddressAdded), e)
}

// PublishAddressDeleted mocks base method.
func (m *MockEventPublisher) PublishAddressDeleted(e *event.AddressDeletedEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishAddressDeleted", e)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishAddressDeleted indicates an expected call of PublishAddressDeleted.
func (mr *MockEventPublisherMockRecorder) PublishAddressDeleted(e any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishAddressDeleted", reflect.TypeOf((*MockEventPublisher)(nil).PublishAddressDeleted), e)
}

// PublishAddressUpdated mocks base method.
func (m *MockEventPublisher) PublishAddressUpdated(e *event.AddressUpdatedEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishAddressUpdated", e)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishAddressUpdated indicates an expected call of PublishAddressUpdated.
func (mr *MockEventPublisherMockRecorder) PublishAddressUpdated(e any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishAddressUpdated", reflect.TypeOf((*MockEventPublisher)(nil).PublishAddressUpdated), e)
}

// PublishUserInfoUpdated mocks base method.
func (m *MockEventPublisher) PublishUserInfoUpdated(e *event.UserInfoUpdatedEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishUserInfoUpdated", e)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishUserInfoUpdated indicates an expected call of PublishUserInfoUpdated.
func (mr *MockEventPublisherMockRecorder) PublishUserInfoUpdated(e any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishUserInfoUpdated", reflect.TypeOf((*MockEventPublisher)(nil).PublishUserInfoUpdated), e)
}

// PublishUserLoggedIn mocks base method.
func (m *MockEventPublisher) PublishUserLoggedIn(e *event.UserLoggedInEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishUserLoggedIn", e)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishUserLoggedIn indicates an expected call of PublishUserLoggedIn.
func (mr *MockEventPublisherMockRecorder) PublishUserLoggedIn(e any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishUserLoggedIn", reflect.TypeOf((*MockEventPublisher)(nil).PublishUserLoggedIn), e)
}

// PublishUserLoggedOut mocks base method.
func (m *MockEventPublisher) PublishUserLoggedOut(e *event.UserLoggedOutEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishUserLoggedOut", e)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishUserLoggedOut indicates an expected call of PublishUserLoggedOut.
func (mr *MockEventPublisherMockRecorder) PublishUserLoggedOut(e any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishUserLoggedOut", reflect.TypeOf((*MockEventPublisher)(nil).PublishUserLoggedOut), e)
}

// PublishUserRegistered mocks base method.
func (m *MockEventPublisher) PublishUserRegistered(e *event.UserRegisteredEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishUserRegistered", e)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishUserRegistered indicates an expected call of PublishUserRegistered.
func (mr *MockEventPublisherMockRecorder) PublishUserRegistered(e any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishUserRegistered", reflect.TypeOf((*MockEventPublisher)(nil).PublishUserRegistered), e)
}
