// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.1
// Source: auths.proto

package server

import (
	"context"

	"github.com/falconfan123/Go-mall/services/auths/internal/logic"
	"github.com/falconfan123/Go-mall/services/auths/internal/svc"
	auths "github.com/falconfan123/Go-mall/services/auths/pb"
)

type AuthsServer struct {
	svcCtx *svc.ServiceContext
	auths.UnimplementedAuthsServer
}

func NewAuthsServer(svcCtx *svc.ServiceContext) *AuthsServer {
	return &AuthsServer{
		svcCtx: svcCtx,
	}
}

// Authentication 验证用户token合法
func (s *AuthsServer) Authentication(ctx context.Context, in *auths.AuthReq) (*auths.AuthsRes, error) {
	l := logic.NewAuthenticationLogic(ctx, s.svcCtx)
	return l.Authentication(in)
}

// GenerateToken 生成token
func (s *AuthsServer) GenerateToken(ctx context.Context, in *auths.AuthGenReq) (*auths.AuthGenRes, error) {
	l := logic.NewGenerateTokenLogic(ctx, s.svcCtx)
	return l.GenerateToken(in)
}

// RenewToken 续期身份
func (s *AuthsServer) RenewToken(ctx context.Context, in *auths.AuthRenewalReq) (*auths.AuthRenewalRes, error) {
	l := logic.NewRenewTokenLogic(ctx, s.svcCtx)
	return l.RenewToken(in)
}

// ValidateToken 验证长短令牌（用于网关）
func (s *AuthsServer) ValidateToken(ctx context.Context, in *auths.AuthValidateReq) (*auths.AuthValidateRes, error) {
	l := logic.NewValidateTokenLogic(ctx, s.svcCtx)
	return l.ValidateToken(in)
}

// Logout 登出（删除Session）
func (s *AuthsServer) Logout(ctx context.Context, in *auths.LogoutReq) (*auths.LogoutRes, error) {
	l := logic.NewLogoutLogic(ctx, s.svcCtx)
	return l.Logout(in)
}
