// Code generated by MockGen. DO NOT EDIT.
// Source: services/audit/internal/domain/repository/audit_repository.go
//
// Generated by this command:
//
//	mockgen -source services/audit/internal/domain/repository/audit_repository.go -package testmock -destination services/audit/internal/testmock/mock_audit_repository.go
//

// Package testmock is a generated GoMock package.
package testmock

import (
	context "context"
	reflect "reflect"

	entity "github.com/falconfan123/Go-mall/services/audit/internal/domain/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockAuditRepository is a mock of AuditRepository interface.
type MockAuditRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAuditRepositoryMockRecorder
	isgomock struct{}
}

// MockAuditRepositoryMockRecorder is the mock recorder for MockAuditRepository.
type MockAuditRepositoryMockRecorder struct {
	mock *MockAuditRepository
}

// NewMockAuditRepository creates a new mock instance.
func NewMockAuditRepository(ctrl *gomock.Controller) *MockAuditRepository {
	mock := &MockAuditRepository{ctrl: ctrl}
	mock.recorder = &MockAuditRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuditRepository) EXPECT() *MockAuditRepositoryMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockAuditRepository) Delete(ctx context.Context, id uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockAuditRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockAuditRepository)(nil).Delete), ctx, id)
}

// GetByID mocks base method.
func (m *MockAuditRepository) GetByID(ctx context.Context, id uint64) (*entity.AuditLog, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*entity.AuditLog)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockAuditRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockAuditRepository)(nil).GetByID), ctx, id)
}

// GetByTraceID mocks base method.
func (m *MockAuditRepository) GetByTraceID(ctx context.Context, traceID string) (*entity.AuditLog, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByTraceID", ctx, traceID)
	ret0, _ := ret[0].(*entity.AuditLog)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByTraceID indicates an expected call of GetByTraceID.
func (mr *MockAuditRepositoryMockRecorder) GetByTraceID(ctx, traceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByTraceID", reflect.TypeOf((*MockAuditRepository)(nil).GetByTraceID), ctx, traceID)
}

// ListByActionType mocks base method.
func (m *MockAuditRepository) ListByActionType(ctx context.Context, actionType string, page, pageSize int) ([]*entity.AuditLog, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByActionType", ctx, actionType, page, pageSize)
	ret0, _ := ret[0].([]*entity.AuditLog)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListByActionType indicates an expected call of ListByActionType.
func (mr *MockAuditRepositoryMockRecorder) ListByActionType(ctx, actionType, page, pageSize any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByActionType", reflect.TypeOf((*MockAuditRepository)(nil).ListByActionType), ctx, actionType, page, pageSize)
}

// ListByTarget mocks base method.
func (m *MockAuditRepository) ListByTarget(ctx context.Context, targetTable string, targetID uint64, page, pageSize int) ([]*entity.AuditLog, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByTarget", ctx, targetTable, targetID, page, pageSize)
	ret0, _ := ret[0].([]*entity.AuditLog)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListByTarget indicates an expected call of ListByTarget.
func (mr *MockAuditRepositoryMockRecorder) ListByTarget(ctx, targetTable, targetID, page, pageSize any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByTarget", reflect.TypeOf((*MockAuditRepository)(nil).ListByTarget), ctx, targetTable, targetID, page, pageSize)
}

// ListByUserID mocks base method.
func (m *MockAuditRepository) ListByUserID(ctx context.Context, userID uint64, page, pageSize int) ([]*entity.AuditLog, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByUserID", ctx, userID, page, pageSize)
	ret0, _ := ret[0].([]*entity.AuditLog)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListByUserID indicates an expected call of ListByUserID.
func (mr *MockAuditRepositoryMockRecorder) ListByUserID(ctx, userID, page, pageSize any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByUserID", reflect.TypeOf((*MockAuditRepository)(nil).ListByUserID), ctx, userID, page, pageSize)
}

// Save mocks base method.
func (m *MockAuditRepository) Save(ctx context.Context, auditLog *entity.AuditLog) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, auditLog)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockAuditRepositoryMockRecorder) Save(ctx, auditLog any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockAuditRepository)(nil).Save), ctx, auditLog)
}
