// Code generated by goctl. DO NOT EDIT.

package order

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	orderItemsFieldNames          = builder.RawFieldNames(&OrderItems{}, true) // PostgreSQL mode
	orderItemsRows                = strings.Join(orderItemsFieldNames, ",")
	orderItemsRowsExpectAutoSet   = strings.Join(stringx.Remove(orderItemsFieldNames, "created_at"), ",")
	orderItemsRowsWithPlaceHolder = strings.Join(stringx.Remove(orderItemsFieldNames, "order_id", "created_at"), "=?,") + "=?"
)

type (
	orderItemsModel interface {
		Insert(ctx context.Context, data *OrderItems) (sql.Result, error)
		FindOne(ctx context.Context, orderId string) (*OrderItems, error)
		Update(ctx context.Context, data *OrderItems) error
		Delete(ctx context.Context, orderId string) error
	}

	defaultOrderItemsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	OrderItems struct {
		OrderId     string    `db:"order_id"`     // 预订单ID
		ProductId   uint64    `db:"product_id"`   // 商品ID
		Quantity    uint64    `db:"quantity"`     // 数量
		Price       int64     `db:"price"`        // 当时单价（分）
		ProductName string    `db:"product_name"` // 商品名称
		ProductDesc string    `db:"product_desc"` // 商品描述
		CreatedAt   time.Time `db:"created_at"`
	}
)

func newOrderItemsModel(conn sqlx.SqlConn) *defaultOrderItemsModel {
	return &defaultOrderItemsModel{
		conn:  conn,
		table: "order_items",
	}
}

func (m *defaultOrderItemsModel) Delete(ctx context.Context, orderId string) error {
	query := fmt.Sprintf("delete from %s where \"order_id\" = $1", m.table)
	_, err := m.conn.ExecCtx(ctx, query, orderId)
	return err
}

func (m *defaultOrderItemsModel) FindOne(ctx context.Context, orderId string) (*OrderItems, error) {
	query := fmt.Sprintf("select %s from %s where \"order_id\" = $1 limit 1", orderItemsRows, m.table)
	var resp OrderItems
	err := m.conn.QueryRowCtx(ctx, &resp, query, orderId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultOrderItemsModel) Insert(ctx context.Context, data *OrderItems) (sql.Result, error) {
	// Use PostgreSQL $1, $2, ... placeholders
	fields := strings.Split(orderItemsRowsExpectAutoSet, ",")
	placeholders := make([]string, len(fields))
	for i := range fields {
		placeholders[i] = fmt.Sprintf("$%d", i+1)
	}
	query := fmt.Sprintf("insert into %s (%s) values (%s)", m.table, orderItemsRowsExpectAutoSet, strings.Join(placeholders, ", "))
	ret, err := m.conn.ExecCtx(ctx, query, data.OrderId, data.ProductId, data.Quantity, data.Price, data.ProductName, data.ProductDesc)
	return ret, err
}

func (m *defaultOrderItemsModel) Update(ctx context.Context, data *OrderItems) error {
	// Use PostgreSQL $1, $2, ... placeholders
	fields := strings.Split(orderItemsRowsWithPlaceHolder, "=?")
	setClauses := make([]string, 0, len(fields))
	for i, f := range fields {
		if f != "" {
			setClauses = append(setClauses, fmt.Sprintf("%s = $%d", f, i+1))
		}
	}
	query := fmt.Sprintf("update %s set %s where \"order_id\" = $%d", m.table, strings.Join(setClauses, ", "), len(setClauses)+1)
	_, err := m.conn.ExecCtx(ctx, query, data.ProductId, data.Quantity, data.Price, data.ProductName, data.ProductDesc, data.OrderId)
	return err
}

func (m *defaultOrderItemsModel) tableName() string {
	return m.table
}
