// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: carts.proto

package carts

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInfo) Reset() {
	*x = UserInfo{}
	mi := &file_carts_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfo) ProtoMessage() {}

func (x *UserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_carts_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfo.ProtoReflect.Descriptor instead.
func (*UserInfo) Descriptor() ([]byte, []int) {
	return file_carts_proto_rawDescGZIP(), []int{0}
}

func (x *UserInfo) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type CartItemListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	StatusMsg     string                 `protobuf:"bytes,2,opt,name=status_msg,json=statusMsg,proto3" json:"status_msg,omitempty"`
	Total         int32                  `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	Data          []*CartInfoResponse    `protobuf:"bytes,4,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CartItemListResponse) Reset() {
	*x = CartItemListResponse{}
	mi := &file_carts_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CartItemListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CartItemListResponse) ProtoMessage() {}

func (x *CartItemListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_carts_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CartItemListResponse.ProtoReflect.Descriptor instead.
func (*CartItemListResponse) Descriptor() ([]byte, []int) {
	return file_carts_proto_rawDescGZIP(), []int{1}
}

func (x *CartItemListResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *CartItemListResponse) GetStatusMsg() string {
	if x != nil {
		return x.StatusMsg
	}
	return ""
}

func (x *CartItemListResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *CartItemListResponse) GetData() []*CartInfoResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

type CartInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int32                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ProductId     int32                  `protobuf:"varint,3,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	ProductName   string                 `protobuf:"bytes,4,opt,name=product_name,json=productName,proto3" json:"product_name,omitempty"`
	ProductImage  string                 `protobuf:"bytes,5,opt,name=product_image,json=productImage,proto3" json:"product_image,omitempty"`
	ProductPrice  float32                `protobuf:"fixed32,6,opt,name=product_price,json=productPrice,proto3" json:"product_price,omitempty"`
	Quantity      int32                  `protobuf:"varint,7,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Checked       bool                   `protobuf:"varint,8,opt,name=checked,proto3" json:"checked,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CartInfoResponse) Reset() {
	*x = CartInfoResponse{}
	mi := &file_carts_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CartInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CartInfoResponse) ProtoMessage() {}

func (x *CartInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_carts_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CartInfoResponse.ProtoReflect.Descriptor instead.
func (*CartInfoResponse) Descriptor() ([]byte, []int) {
	return file_carts_proto_rawDescGZIP(), []int{2}
}

func (x *CartInfoResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CartInfoResponse) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CartInfoResponse) GetProductId() int32 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *CartInfoResponse) GetProductName() string {
	if x != nil {
		return x.ProductName
	}
	return ""
}

func (x *CartInfoResponse) GetProductImage() string {
	if x != nil {
		return x.ProductImage
	}
	return ""
}

func (x *CartInfoResponse) GetProductPrice() float32 {
	if x != nil {
		return x.ProductPrice
	}
	return 0
}

func (x *CartInfoResponse) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *CartInfoResponse) GetChecked() bool {
	if x != nil {
		return x.Checked
	}
	return false
}

type CreateCartResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	StatusMsg     string                 `protobuf:"bytes,2,opt,name=status_msg,json=statusMsg,proto3" json:"status_msg,omitempty"`
	Id            int32                  `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCartResponse) Reset() {
	*x = CreateCartResponse{}
	mi := &file_carts_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCartResponse) ProtoMessage() {}

func (x *CreateCartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_carts_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCartResponse.ProtoReflect.Descriptor instead.
func (*CreateCartResponse) Descriptor() ([]byte, []int) {
	return file_carts_proto_rawDescGZIP(), []int{3}
}

func (x *CreateCartResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *CreateCartResponse) GetStatusMsg() string {
	if x != nil {
		return x.StatusMsg
	}
	return ""
}

func (x *CreateCartResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type SubCartResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	StatusMsg     string                 `protobuf:"bytes,2,opt,name=status_msg,json=statusMsg,proto3" json:"status_msg,omitempty"`
	Id            int32                  `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubCartResponse) Reset() {
	*x = SubCartResponse{}
	mi := &file_carts_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubCartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubCartResponse) ProtoMessage() {}

func (x *SubCartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_carts_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubCartResponse.ProtoReflect.Descriptor instead.
func (*SubCartResponse) Descriptor() ([]byte, []int) {
	return file_carts_proto_rawDescGZIP(), []int{4}
}

func (x *SubCartResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *SubCartResponse) GetStatusMsg() string {
	if x != nil {
		return x.StatusMsg
	}
	return ""
}

func (x *SubCartResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type CartItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int32                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ProductId     int32                  `protobuf:"varint,3,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	ProductName   string                 `protobuf:"bytes,4,opt,name=product_name,json=productName,proto3" json:"product_name,omitempty"`
	ProductImage  string                 `protobuf:"bytes,5,opt,name=product_image,json=productImage,proto3" json:"product_image,omitempty"`
	ProductPrice  float32                `protobuf:"fixed32,6,opt,name=productPrice,proto3" json:"productPrice,omitempty"`
	Quantity      int32                  `protobuf:"varint,7,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Checked       bool                   `protobuf:"varint,8,opt,name=checked,proto3" json:"checked,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CartItemRequest) Reset() {
	*x = CartItemRequest{}
	mi := &file_carts_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CartItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CartItemRequest) ProtoMessage() {}

func (x *CartItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_carts_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CartItemRequest.ProtoReflect.Descriptor instead.
func (*CartItemRequest) Descriptor() ([]byte, []int) {
	return file_carts_proto_rawDescGZIP(), []int{5}
}

func (x *CartItemRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CartItemRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CartItemRequest) GetProductId() int32 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *CartItemRequest) GetProductName() string {
	if x != nil {
		return x.ProductName
	}
	return ""
}

func (x *CartItemRequest) GetProductImage() string {
	if x != nil {
		return x.ProductImage
	}
	return ""
}

func (x *CartItemRequest) GetProductPrice() float32 {
	if x != nil {
		return x.ProductPrice
	}
	return 0
}

func (x *CartItemRequest) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *CartItemRequest) GetChecked() bool {
	if x != nil {
		return x.Checked
	}
	return false
}

type EmptyCartResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	StatusMsg     string                 `protobuf:"bytes,2,opt,name=status_msg,json=statusMsg,proto3" json:"status_msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyCartResponse) Reset() {
	*x = EmptyCartResponse{}
	mi := &file_carts_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyCartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyCartResponse) ProtoMessage() {}

func (x *EmptyCartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_carts_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyCartResponse.ProtoReflect.Descriptor instead.
func (*EmptyCartResponse) Descriptor() ([]byte, []int) {
	return file_carts_proto_rawDescGZIP(), []int{6}
}

func (x *EmptyCartResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *EmptyCartResponse) GetStatusMsg() string {
	if x != nil {
		return x.StatusMsg
	}
	return ""
}

var File_carts_proto protoreflect.FileDescriptor

const file_carts_proto_rawDesc = "" +
	"\n" +
	"\vcarts.proto\x12\x05carts\"\x1a\n" +
	"\bUserInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"\x99\x01\n" +
	"\x14CartItemListResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x1d\n" +
	"\n" +
	"status_msg\x18\x02 \x01(\tR\tstatusMsg\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x05R\x05total\x12+\n" +
	"\x04data\x18\x04 \x03(\v2\x17.carts.CartInfoResponseR\x04data\"\xfd\x01\n" +
	"\x10CartInfoResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x05R\x06userId\x12\x1d\n" +
	"\n" +
	"product_id\x18\x03 \x01(\x05R\tproductId\x12!\n" +
	"\fproduct_name\x18\x04 \x01(\tR\vproductName\x12#\n" +
	"\rproduct_image\x18\x05 \x01(\tR\fproductImage\x12#\n" +
	"\rproduct_price\x18\x06 \x01(\x02R\fproductPrice\x12\x1a\n" +
	"\bquantity\x18\a \x01(\x05R\bquantity\x12\x18\n" +
	"\achecked\x18\b \x01(\bR\achecked\"d\n" +
	"\x12CreateCartResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x1d\n" +
	"\n" +
	"status_msg\x18\x02 \x01(\tR\tstatusMsg\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\x05R\x02id\"a\n" +
	"\x0fSubCartResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x1d\n" +
	"\n" +
	"status_msg\x18\x02 \x01(\tR\tstatusMsg\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\x05R\x02id\"\xfb\x01\n" +
	"\x0fCartItemRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x05R\x06userId\x12\x1d\n" +
	"\n" +
	"product_id\x18\x03 \x01(\x05R\tproductId\x12!\n" +
	"\fproduct_name\x18\x04 \x01(\tR\vproductName\x12#\n" +
	"\rproduct_image\x18\x05 \x01(\tR\fproductImage\x12\"\n" +
	"\fproductPrice\x18\x06 \x01(\x02R\fproductPrice\x12\x1a\n" +
	"\bquantity\x18\a \x01(\x05R\bquantity\x12\x18\n" +
	"\achecked\x18\b \x01(\bR\achecked\"S\n" +
	"\x11EmptyCartResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x1d\n" +
	"\n" +
	"status_msg\x18\x02 \x01(\tR\tstatusMsg2\x8c\x02\n" +
	"\x04Cart\x12<\n" +
	"\fCartItemList\x12\x0f.carts.UserInfo\x1a\x1b.carts.CartItemListResponse\x12C\n" +
	"\x0eCreateCartItem\x12\x16.carts.CartItemRequest\x1a\x19.carts.CreateCartResponse\x12=\n" +
	"\vSubCartItem\x12\x16.carts.CartItemRequest\x1a\x16.carts.SubCartResponse\x12B\n" +
	"\x0eDeleteCartItem\x12\x16.carts.CartItemRequest\x1a\x18.carts.EmptyCartResponseB\tZ\a./cartsb\x06proto3"

var (
	file_carts_proto_rawDescOnce sync.Once
	file_carts_proto_rawDescData []byte
)

func file_carts_proto_rawDescGZIP() []byte {
	file_carts_proto_rawDescOnce.Do(func() {
		file_carts_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_carts_proto_rawDesc), len(file_carts_proto_rawDesc)))
	})
	return file_carts_proto_rawDescData
}

var file_carts_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_carts_proto_goTypes = []any{
	(*UserInfo)(nil),             // 0: carts.UserInfo
	(*CartItemListResponse)(nil), // 1: carts.CartItemListResponse
	(*CartInfoResponse)(nil),     // 2: carts.CartInfoResponse
	(*CreateCartResponse)(nil),   // 3: carts.CreateCartResponse
	(*SubCartResponse)(nil),      // 4: carts.SubCartResponse
	(*CartItemRequest)(nil),      // 5: carts.CartItemRequest
	(*EmptyCartResponse)(nil),    // 6: carts.EmptyCartResponse
}
var file_carts_proto_depIdxs = []int32{
	2, // 0: carts.CartItemListResponse.data:type_name -> carts.CartInfoResponse
	0, // 1: carts.Cart.CartItemList:input_type -> carts.UserInfo
	5, // 2: carts.Cart.CreateCartItem:input_type -> carts.CartItemRequest
	5, // 3: carts.Cart.SubCartItem:input_type -> carts.CartItemRequest
	5, // 4: carts.Cart.DeleteCartItem:input_type -> carts.CartItemRequest
	1, // 5: carts.Cart.CartItemList:output_type -> carts.CartItemListResponse
	3, // 6: carts.Cart.CreateCartItem:output_type -> carts.CreateCartResponse
	4, // 7: carts.Cart.SubCartItem:output_type -> carts.SubCartResponse
	6, // 8: carts.Cart.DeleteCartItem:output_type -> carts.EmptyCartResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_carts_proto_init() }
func file_carts_proto_init() {
	if File_carts_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_carts_proto_rawDesc), len(file_carts_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_carts_proto_goTypes,
		DependencyIndexes: file_carts_proto_depIdxs,
		MessageInfos:      file_carts_proto_msgTypes,
	}.Build()
	File_carts_proto = out.File
	file_carts_proto_goTypes = nil
	file_carts_proto_depIdxs = nil
}
