// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.1
// Source: product.proto

package productcatalogservice

import (
	"context"

	"services/product/product/product/product"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CreateProductReq              = pb.CreateProductReq
	CreateProductResp             = pb.CreateProductResp
	DeleteProductReq              = pb.DeleteProductReq
	DeleteProductResp             = pb.DeleteProductResp
	GetAllProductsReq             = pb.GetAllProductsReq
	GetAllProductsResp            = pb.GetAllProductsResp
	GetProductReq                 = pb.GetProductReq
	GetProductResp                = pb.GetProductResp
	GetUploadURLReq               = pb.GetUploadURLReq
	GetUploadURLResp              = pb.GetUploadURLResp
	IsExistProductReq             = pb.IsExistProductReq
	IsExistProductResp            = pb.IsExistProductResp
	ListProductsReq               = pb.ListProductsReq
	ListProductsResp              = pb.ListProductsResp
	Product                       = pb.Product
	QueryProductReq               = pb.QueryProductReq
	QueryProductReq_Paginator     = pb.QueryProductReq_Paginator
	QueryProductReq_Price         = pb.QueryProductReq_Price
	RecommendProductReq           = pb.RecommendProductReq
	RecommendProductReq_Paginator = pb.RecommendProductReq_Paginator
	UpdateProductReq              = pb.UpdateProductReq
	UpdateProductResp             = pb.UpdateProductResp

	ProductCatalogService interface {
		// 根据商品id得到商品详细信息
		GetProduct(ctx context.Context, in *GetProductReq, opts ...grpc.CallOption) (*GetProductResp, error)
		// 添加新商品
		CreateProduct(ctx context.Context, in *CreateProductReq, opts ...grpc.CallOption) (*CreateProductResp, error)
		// 修改商品
		UpdateProduct(ctx context.Context, in *UpdateProductReq, opts ...grpc.CallOption) (*UpdateProductResp, error)
		// 删除商品
		DeleteProduct(ctx context.Context, in *DeleteProductReq, opts ...grpc.CallOption) (*DeleteProductResp, error)
		// 分页得到全部商品
		GetAllProduct(ctx context.Context, in *GetAllProductsReq, opts ...grpc.CallOption) (*GetAllProductsResp, error)
		// 判断商品是否存在
		IsExistProduct(ctx context.Context, in *IsExistProductReq, opts ...grpc.CallOption) (*IsExistProductResp, error)
		// 根据条件查询商品
		QueryProduct(ctx context.Context, in *QueryProductReq, opts ...grpc.CallOption) (*GetAllProductsResp, error)
		RecommendProduct(ctx context.Context, in *RecommendProductReq, opts ...grpc.CallOption) (*GetAllProductsResp, error)
		// MinIO 预签名上传接口
		GetUploadURL(ctx context.Context, in *GetUploadURLReq, opts ...grpc.CallOption) (*GetUploadURLResp, error)
		// 高性能游标分页接口
		ListProducts(ctx context.Context, in *ListProductsReq, opts ...grpc.CallOption) (*ListProductsResp, error)
	}

	defaultProductCatalogService struct {
		cli zrpc.Client
	}
)

func NewProductCatalogService(cli zrpc.Client) ProductCatalogService {
	return &defaultProductCatalogService{
		cli: cli,
	}
}

// 根据商品id得到商品详细信息
func (m *defaultProductCatalogService) GetProduct(ctx context.Context, in *GetProductReq, opts ...grpc.CallOption) (*GetProductResp, error) {
	client := pb.NewProductCatalogServiceClient(m.cli.Conn())
	return client.GetProduct(ctx, in, opts...)
}

// 添加新商品
func (m *defaultProductCatalogService) CreateProduct(ctx context.Context, in *CreateProductReq, opts ...grpc.CallOption) (*CreateProductResp, error) {
	client := pb.NewProductCatalogServiceClient(m.cli.Conn())
	return client.CreateProduct(ctx, in, opts...)
}

// 修改商品
func (m *defaultProductCatalogService) UpdateProduct(ctx context.Context, in *UpdateProductReq, opts ...grpc.CallOption) (*UpdateProductResp, error) {
	client := pb.NewProductCatalogServiceClient(m.cli.Conn())
	return client.UpdateProduct(ctx, in, opts...)
}

// 删除商品
func (m *defaultProductCatalogService) DeleteProduct(ctx context.Context, in *DeleteProductReq, opts ...grpc.CallOption) (*DeleteProductResp, error) {
	client := pb.NewProductCatalogServiceClient(m.cli.Conn())
	return client.DeleteProduct(ctx, in, opts...)
}

// 分页得到全部商品
func (m *defaultProductCatalogService) GetAllProduct(ctx context.Context, in *GetAllProductsReq, opts ...grpc.CallOption) (*GetAllProductsResp, error) {
	client := pb.NewProductCatalogServiceClient(m.cli.Conn())
	return client.GetAllProduct(ctx, in, opts...)
}

// 判断商品是否存在
func (m *defaultProductCatalogService) IsExistProduct(ctx context.Context, in *IsExistProductReq, opts ...grpc.CallOption) (*IsExistProductResp, error) {
	client := pb.NewProductCatalogServiceClient(m.cli.Conn())
	return client.IsExistProduct(ctx, in, opts...)
}

// 根据条件查询商品
func (m *defaultProductCatalogService) QueryProduct(ctx context.Context, in *QueryProductReq, opts ...grpc.CallOption) (*GetAllProductsResp, error) {
	client := pb.NewProductCatalogServiceClient(m.cli.Conn())
	return client.QueryProduct(ctx, in, opts...)
}

func (m *defaultProductCatalogService) RecommendProduct(ctx context.Context, in *RecommendProductReq, opts ...grpc.CallOption) (*GetAllProductsResp, error) {
	client := pb.NewProductCatalogServiceClient(m.cli.Conn())
	return client.RecommendProduct(ctx, in, opts...)
}

// MinIO 预签名上传接口
func (m *defaultProductCatalogService) GetUploadURL(ctx context.Context, in *GetUploadURLReq, opts ...grpc.CallOption) (*GetUploadURLResp, error) {
	client := pb.NewProductCatalogServiceClient(m.cli.Conn())
	return client.GetUploadURL(ctx, in, opts...)
}

// 高性能游标分页接口
func (m *defaultProductCatalogService) ListProducts(ctx context.Context, in *ListProductsReq, opts ...grpc.CallOption) (*ListProductsResp, error) {
	client := pb.NewProductCatalogServiceClient(m.cli.Conn())
	return client.ListProducts(ctx, in, opts...)
}
