// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.1

package product_categories

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	productCategoriesFieldNames          = builder.RawFieldNames(&ProductCategories{}, true)
	productCategoriesRows                = strings.Join(productCategoriesFieldNames, ",")
	productCategoriesRowsExpectAutoSet   = strings.Join(stringx.Remove(productCategoriesFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	productCategoriesRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(productCategoriesFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))
)

type (
	productCategoriesModel interface {
		Insert(ctx context.Context, data *ProductCategories) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*ProductCategories, error)
		FindOneByProductIdCategoryId(ctx context.Context, productId sql.NullInt64, categoryId sql.NullInt64) (*ProductCategories, error)
		Update(ctx context.Context, data *ProductCategories) error
		Delete(ctx context.Context, id int64) error
	}

	defaultProductCategoriesModel struct {
		conn  sqlx.SqlConn
		table string
	}

	ProductCategories struct {
		Id         int64         `db:"id"`
		ProductId  sql.NullInt64 `db:"product_id"`
		CategoryId sql.NullInt64 `db:"category_id"`
	}
)

func newProductCategoriesModel(conn sqlx.SqlConn) *defaultProductCategoriesModel {
	return &defaultProductCategoriesModel{
		conn:  conn,
		table: `"public"."product_categories"`,
	}
}

func (m *defaultProductCategoriesModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where id = $1", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultProductCategoriesModel) FindOne(ctx context.Context, id int64) (*ProductCategories, error) {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", productCategoriesRows, m.table)
	var resp ProductCategories
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultProductCategoriesModel) FindOneByProductIdCategoryId(ctx context.Context, productId sql.NullInt64, categoryId sql.NullInt64) (*ProductCategories, error) {
	var resp ProductCategories
	query := fmt.Sprintf("select %s from %s where product_id = $1 and category_id = $2 limit 1", productCategoriesRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, productId, categoryId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultProductCategoriesModel) Insert(ctx context.Context, data *ProductCategories) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values ($1, $2)", m.table, productCategoriesRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.ProductId, data.CategoryId)
	return ret, err
}

func (m *defaultProductCategoriesModel) Update(ctx context.Context, newData *ProductCategories) error {
	query := fmt.Sprintf("update %s set %s where id = $1", m.table, productCategoriesRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.Id, newData.ProductId, newData.CategoryId)
	return err
}

func (m *defaultProductCategoriesModel) tableName() string {
	return m.table
}
