// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.5
// Source: carts.proto

package cartsclient

import (
	"context"

	"github.com/falconfan123/Go-mall/services/carts/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CartInfoResponse     = pb.CartInfoResponse
	CartItemListResponse = pb.CartItemListResponse
	CreateCartResponse   = pb.CreateCartResponse
	SubCartResponse      = pb.SubCartResponse
	CartItemRequest      = pb.CartItemRequest
	EmptyCartResponse    = pb.EmptyCartResponse
	UserInfo             = pb.UserInfo

	Cart interface {
		CartItemList(ctx context.Context, in *UserInfo, opts ...grpc.CallOption) (*CartItemListResponse, error)
		CreateCartItem(ctx context.Context, in *CartItemRequest, opts ...grpc.CallOption) (*CreateCartResponse, error)
		SubCartItem(ctx context.Context, in *CartItemRequest, opts ...grpc.CallOption) (*SubCartResponse, error)
		DeleteCartItem(ctx context.Context, in *CartItemRequest, opts ...grpc.CallOption) (*EmptyCartResponse, error)
	}

	defaultCart struct {
		cli zrpc.Client
	}
)

func NewCart(cli zrpc.Client) Cart {
	return &defaultCart{
		cli: cli,
	}
}

func (m *defaultCart) CartItemList(ctx context.Context, in *UserInfo, opts ...grpc.CallOption) (*CartItemListResponse, error) {
	client := pb.NewCartClient(m.cli.Conn())
	return client.CartItemList(ctx, in, opts...)
}

func (m *defaultCart) CreateCartItem(ctx context.Context, in *CartItemRequest, opts ...grpc.CallOption) (*CreateCartResponse, error) {
	client := pb.NewCartClient(m.cli.Conn())
	return client.CreateCartItem(ctx, in, opts...)
}
func (m *defaultCart) SubCartItem(ctx context.Context, in *CartItemRequest, opts ...grpc.CallOption) (*SubCartResponse, error) {
	client := pb.NewCartClient(m.cli.Conn())
	return client.SubCartItem(ctx, in, opts...)
}

func (m *defaultCart) DeleteCartItem(ctx context.Context, in *CartItemRequest, opts ...grpc.CallOption) (*EmptyCartResponse, error) {
	client := pb.NewCartClient(m.cli.Conn())
	return client.DeleteCartItem(ctx, in, opts...)
}
