// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.1
// Source: system.proto

package server

import (
	"context"

	"github.com/falconfan123/Go-mall/services/system/internal/logic"
	"github.com/falconfan123/Go-mall/services/system/internal/svc"
	"github.com/falconfan123/Go-mall/services/system/pb"
)

type SystemServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedSystemServer
}

func NewSystemServer(svcCtx *svc.ServiceContext) *SystemServer {
	return &SystemServer{
		svcCtx: svcCtx,
	}
}

// Time 获取服务器当前时间戳
func (s *SystemServer) Time(ctx context.Context, in *pb.TimeReq) (*pb.TimeResp, error) {
	l := logic.NewTimeLogic(ctx, s.svcCtx)
	return l.Time(in)
}
