// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: product.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetUploadURLReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	ContentType   string                 `protobuf:"bytes,2,opt,name=contentType,proto3" json:"contentType,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUploadURLReq) Reset() {
	*x = GetUploadURLReq{}
	mi := &file_product_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUploadURLReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUploadURLReq) ProtoMessage() {}

func (x *GetUploadURLReq) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUploadURLReq.ProtoReflect.Descriptor instead.
func (*GetUploadURLReq) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{0}
}

func (x *GetUploadURLReq) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *GetUploadURLReq) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

type GetUploadURLResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UploadUrl     string                 `protobuf:"bytes,1,opt,name=uploadUrl,proto3" json:"uploadUrl,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	FormData      map[string]string      `protobuf:"bytes,3,rep,name=formData,proto3" json:"formData,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	StatusCode    uint32                 `protobuf:"varint,4,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	StatusMsg     string                 `protobuf:"bytes,5,opt,name=status_msg,json=statusMsg,proto3" json:"status_msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUploadURLResp) Reset() {
	*x = GetUploadURLResp{}
	mi := &file_product_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUploadURLResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUploadURLResp) ProtoMessage() {}

func (x *GetUploadURLResp) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUploadURLResp.ProtoReflect.Descriptor instead.
func (*GetUploadURLResp) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{1}
}

func (x *GetUploadURLResp) GetUploadUrl() string {
	if x != nil {
		return x.UploadUrl
	}
	return ""
}

func (x *GetUploadURLResp) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *GetUploadURLResp) GetFormData() map[string]string {
	if x != nil {
		return x.FormData
	}
	return nil
}

func (x *GetUploadURLResp) GetStatusCode() uint32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *GetUploadURLResp) GetStatusMsg() string {
	if x != nil {
		return x.StatusMsg
	}
	return ""
}

type ListProductsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cursor        int64                  `protobuf:"varint,1,opt,name=cursor,proto3" json:"cursor,omitempty"` // 上一次返回的最后一个商品ID，第一页传0
	Limit         int64                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProductsReq) Reset() {
	*x = ListProductsReq{}
	mi := &file_product_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProductsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductsReq) ProtoMessage() {}

func (x *ListProductsReq) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductsReq.ProtoReflect.Descriptor instead.
func (*ListProductsReq) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{2}
}

func (x *ListProductsReq) GetCursor() int64 {
	if x != nil {
		return x.Cursor
	}
	return 0
}

func (x *ListProductsReq) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListProductsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Products      []*Product             `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	NextCursor    int64                  `protobuf:"varint,2,opt,name=nextCursor,proto3" json:"nextCursor,omitempty"`
	HasMore       bool                   `protobuf:"varint,3,opt,name=hasMore,proto3" json:"hasMore,omitempty"`
	StatusCode    uint32                 `protobuf:"varint,4,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	StatusMsg     string                 `protobuf:"bytes,5,opt,name=status_msg,json=statusMsg,proto3" json:"status_msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProductsResp) Reset() {
	*x = ListProductsResp{}
	mi := &file_product_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProductsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductsResp) ProtoMessage() {}

func (x *ListProductsResp) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductsResp.ProtoReflect.Descriptor instead.
func (*ListProductsResp) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{3}
}

func (x *ListProductsResp) GetProducts() []*Product {
	if x != nil {
		return x.Products
	}
	return nil
}

func (x *ListProductsResp) GetNextCursor() int64 {
	if x != nil {
		return x.NextCursor
	}
	return 0
}

func (x *ListProductsResp) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

func (x *ListProductsResp) GetStatusCode() uint32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *ListProductsResp) GetStatusMsg() string {
	if x != nil {
		return x.StatusMsg
	}
	return ""
}

type RecommendProductReq struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	UserId        int32                          `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Paginator     *RecommendProductReq_Paginator `protobuf:"bytes,2,opt,name=paginator,proto3" json:"paginator,omitempty"`
	Category      []string                       `protobuf:"bytes,3,rep,name=category,proto3" json:"category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecommendProductReq) Reset() {
	*x = RecommendProductReq{}
	mi := &file_product_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecommendProductReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecommendProductReq) ProtoMessage() {}

func (x *RecommendProductReq) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecommendProductReq.ProtoReflect.Descriptor instead.
func (*RecommendProductReq) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{4}
}

func (x *RecommendProductReq) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *RecommendProductReq) GetPaginator() *RecommendProductReq_Paginator {
	if x != nil {
		return x.Paginator
	}
	return nil
}

func (x *RecommendProductReq) GetCategory() []string {
	if x != nil {
		return x.Category
	}
	return nil
}

type QueryProductReq struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Name          string                     `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	New           bool                       `protobuf:"varint,2,opt,name=new,proto3" json:"new,omitempty"`
	Hot           bool                       `protobuf:"varint,3,opt,name=hot,proto3" json:"hot,omitempty"`
	Keyword       string                     `protobuf:"bytes,4,opt,name=keyword,proto3" json:"keyword,omitempty"`
	Category      []string                   `protobuf:"bytes,5,rep,name=category,proto3" json:"category,omitempty"`
	Price         *QueryProductReq_Price     `protobuf:"bytes,6,opt,name=price,proto3" json:"price,omitempty"`
	Paginator     *QueryProductReq_Paginator `protobuf:"bytes,7,opt,name=paginator,proto3" json:"paginator,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryProductReq) Reset() {
	*x = QueryProductReq{}
	mi := &file_product_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryProductReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryProductReq) ProtoMessage() {}

func (x *QueryProductReq) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryProductReq.ProtoReflect.Descriptor instead.
func (*QueryProductReq) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{5}
}

func (x *QueryProductReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *QueryProductReq) GetNew() bool {
	if x != nil {
		return x.New
	}
	return false
}

func (x *QueryProductReq) GetHot() bool {
	if x != nil {
		return x.Hot
	}
	return false
}

func (x *QueryProductReq) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *QueryProductReq) GetCategory() []string {
	if x != nil {
		return x.Category
	}
	return nil
}

func (x *QueryProductReq) GetPrice() *QueryProductReq_Price {
	if x != nil {
		return x.Price
	}
	return nil
}

func (x *QueryProductReq) GetPaginator() *QueryProductReq_Paginator {
	if x != nil {
		return x.Paginator
	}
	return nil
}

type Product struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Picture       string                 `protobuf:"bytes,4,opt,name=picture,proto3" json:"picture,omitempty"`
	Price         int64                  `protobuf:"varint,5,opt,name=price,proto3" json:"price,omitempty"` // 使用分作为单位，方便计算，避免精度丢失
	Stock         int64                  `protobuf:"varint,6,opt,name=stock,proto3" json:"stock,omitempty"`
	Sold          int64                  `protobuf:"varint,7,opt,name=sold,proto3" json:"sold,omitempty"`
	Categories    []string               `protobuf:"bytes,8,rep,name=categories,proto3" json:"categories,omitempty"`
	CratedAt      string                 `protobuf:"bytes,9,opt,name=crated_at,json=cratedAt,proto3" json:"crated_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	ThumbnailUrl  string                 `protobuf:"bytes,11,opt,name=thumbnail_url,json=thumbnailUrl,proto3" json:"thumbnail_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Product) Reset() {
	*x = Product{}
	mi := &file_product_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Product) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Product) ProtoMessage() {}

func (x *Product) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Product.ProtoReflect.Descriptor instead.
func (*Product) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{6}
}

func (x *Product) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Product) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Product) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Product) GetPicture() string {
	if x != nil {
		return x.Picture
	}
	return ""
}

func (x *Product) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Product) GetStock() int64 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *Product) GetSold() int64 {
	if x != nil {
		return x.Sold
	}
	return 0
}

func (x *Product) GetCategories() []string {
	if x != nil {
		return x.Categories
	}
	return nil
}

func (x *Product) GetCratedAt() string {
	if x != nil {
		return x.CratedAt
	}
	return ""
}

func (x *Product) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *Product) GetThumbnailUrl() string {
	if x != nil {
		return x.ThumbnailUrl
	}
	return ""
}

type IsExistProductReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"` //商品id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsExistProductReq) Reset() {
	*x = IsExistProductReq{}
	mi := &file_product_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsExistProductReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsExistProductReq) ProtoMessage() {}

func (x *IsExistProductReq) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsExistProductReq.ProtoReflect.Descriptor instead.
func (*IsExistProductReq) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{7}
}

func (x *IsExistProductReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type IsExistProductResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    uint32                 `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"` // 状态码
	StatusMsg     string                 `protobuf:"bytes,2,opt,name=status_msg,json=statusMsg,proto3" json:"status_msg,omitempty"`     // 状态描述
	Exist         bool                   `protobuf:"varint,3,opt,name=exist,proto3" json:"exist,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsExistProductResp) Reset() {
	*x = IsExistProductResp{}
	mi := &file_product_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsExistProductResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsExistProductResp) ProtoMessage() {}

func (x *IsExistProductResp) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsExistProductResp.ProtoReflect.Descriptor instead.
func (*IsExistProductResp) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{8}
}

func (x *IsExistProductResp) GetStatusCode() uint32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *IsExistProductResp) GetStatusMsg() string {
	if x != nil {
		return x.StatusMsg
	}
	return ""
}

func (x *IsExistProductResp) GetExist() bool {
	if x != nil {
		return x.Exist
	}
	return false
}

type GetAllProductsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int64                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int64                  `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllProductsReq) Reset() {
	*x = GetAllProductsReq{}
	mi := &file_product_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllProductsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllProductsReq) ProtoMessage() {}

func (x *GetAllProductsReq) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllProductsReq.ProtoReflect.Descriptor instead.
func (*GetAllProductsReq) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{9}
}

func (x *GetAllProductsReq) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetAllProductsReq) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type GetAllProductsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    uint32                 `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"` // 状态码
	StatusMsg     string                 `protobuf:"bytes,2,opt,name=status_msg,json=statusMsg,proto3" json:"status_msg,omitempty"`     // 状态描述
	Total         int64                  `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	Products      []*Product             `protobuf:"bytes,4,rep,name=products,proto3" json:"products,omitempty"`
	Page          int64                  `protobuf:"varint,5,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int64                  `protobuf:"varint,6,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllProductsResp) Reset() {
	*x = GetAllProductsResp{}
	mi := &file_product_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllProductsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllProductsResp) ProtoMessage() {}

func (x *GetAllProductsResp) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllProductsResp.ProtoReflect.Descriptor instead.
func (*GetAllProductsResp) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{10}
}

func (x *GetAllProductsResp) GetStatusCode() uint32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *GetAllProductsResp) GetStatusMsg() string {
	if x != nil {
		return x.StatusMsg
	}
	return ""
}

func (x *GetAllProductsResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GetAllProductsResp) GetProducts() []*Product {
	if x != nil {
		return x.Products
	}
	return nil
}

func (x *GetAllProductsResp) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetAllProductsResp) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type GetProductReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int32                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductReq) Reset() {
	*x = GetProductReq{}
	mi := &file_product_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductReq) ProtoMessage() {}

func (x *GetProductReq) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductReq.ProtoReflect.Descriptor instead.
func (*GetProductReq) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{11}
}

func (x *GetProductReq) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetProductReq) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetProductResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    uint32                 `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"` // 状态码
	StatusMsg     string                 `protobuf:"bytes,2,opt,name=status_msg,json=statusMsg,proto3" json:"status_msg,omitempty"`     // 状态描述
	Product       *Product               `protobuf:"bytes,3,opt,name=product,proto3" json:"product,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductResp) Reset() {
	*x = GetProductResp{}
	mi := &file_product_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductResp) ProtoMessage() {}

func (x *GetProductResp) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductResp.ProtoReflect.Descriptor instead.
func (*GetProductResp) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{12}
}

func (x *GetProductResp) GetStatusCode() uint32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *GetProductResp) GetStatusMsg() string {
	if x != nil {
		return x.StatusMsg
	}
	return ""
}

func (x *GetProductResp) GetProduct() *Product {
	if x != nil {
		return x.Product
	}
	return nil
}

type CreateProductReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Picture       []byte                 `protobuf:"bytes,3,opt,name=picture,proto3" json:"picture,omitempty"`
	Price         int64                  `protobuf:"varint,4,opt,name=price,proto3" json:"price,omitempty"`
	Stock         int64                  `protobuf:"varint,5,opt,name=stock,proto3" json:"stock,omitempty"`
	Categories    []string               `protobuf:"bytes,6,rep,name=categories,proto3" json:"categories,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProductReq) Reset() {
	*x = CreateProductReq{}
	mi := &file_product_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProductReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProductReq) ProtoMessage() {}

func (x *CreateProductReq) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProductReq.ProtoReflect.Descriptor instead.
func (*CreateProductReq) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{13}
}

func (x *CreateProductReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateProductReq) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateProductReq) GetPicture() []byte {
	if x != nil {
		return x.Picture
	}
	return nil
}

func (x *CreateProductReq) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *CreateProductReq) GetStock() int64 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *CreateProductReq) GetCategories() []string {
	if x != nil {
		return x.Categories
	}
	return nil
}

type CreateProductResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    uint32                 `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"` // 状态码
	StatusMsg     string                 `protobuf:"bytes,2,opt,name=status_msg,json=statusMsg,proto3" json:"status_msg,omitempty"`     // 状态描述
	ProductId     int64                  `protobuf:"varint,3,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`    // 商品id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProductResp) Reset() {
	*x = CreateProductResp{}
	mi := &file_product_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProductResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProductResp) ProtoMessage() {}

func (x *CreateProductResp) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProductResp.ProtoReflect.Descriptor instead.
func (*CreateProductResp) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{14}
}

func (x *CreateProductResp) GetStatusCode() uint32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *CreateProductResp) GetStatusMsg() string {
	if x != nil {
		return x.StatusMsg
	}
	return ""
}

func (x *CreateProductResp) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

type UpdateProductReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Picture       []byte                 `protobuf:"bytes,4,opt,name=picture,proto3" json:"picture,omitempty"`
	Price         int64                  `protobuf:"varint,5,opt,name=price,proto3" json:"price,omitempty"` // 使用分作为单位，方便计算，避免精度丢失
	Stock         int64                  `protobuf:"varint,6,opt,name=stock,proto3" json:"stock,omitempty"`
	Categories    []string               `protobuf:"bytes,8,rep,name=categories,proto3" json:"categories,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProductReq) Reset() {
	*x = UpdateProductReq{}
	mi := &file_product_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProductReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProductReq) ProtoMessage() {}

func (x *UpdateProductReq) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProductReq.ProtoReflect.Descriptor instead.
func (*UpdateProductReq) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{15}
}

func (x *UpdateProductReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateProductReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateProductReq) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateProductReq) GetPicture() []byte {
	if x != nil {
		return x.Picture
	}
	return nil
}

func (x *UpdateProductReq) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *UpdateProductReq) GetStock() int64 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *UpdateProductReq) GetCategories() []string {
	if x != nil {
		return x.Categories
	}
	return nil
}

type UpdateProductResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    uint32                 `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"` // 状态码
	StatusMsg     string                 `protobuf:"bytes,2,opt,name=status_msg,json=statusMsg,proto3" json:"status_msg,omitempty"`     // 状态描述
	Id            int64                  `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`                                   // 商品id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProductResp) Reset() {
	*x = UpdateProductResp{}
	mi := &file_product_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProductResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProductResp) ProtoMessage() {}

func (x *UpdateProductResp) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProductResp.ProtoReflect.Descriptor instead.
func (*UpdateProductResp) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{16}
}

func (x *UpdateProductResp) GetStatusCode() uint32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *UpdateProductResp) GetStatusMsg() string {
	if x != nil {
		return x.StatusMsg
	}
	return ""
}

func (x *UpdateProductResp) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteProductReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProductReq) Reset() {
	*x = DeleteProductReq{}
	mi := &file_product_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProductReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProductReq) ProtoMessage() {}

func (x *DeleteProductReq) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProductReq.ProtoReflect.Descriptor instead.
func (*DeleteProductReq) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{17}
}

func (x *DeleteProductReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteProductResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    uint32                 `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"` // 状态码
	StatusMsg     string                 `protobuf:"bytes,2,opt,name=status_msg,json=statusMsg,proto3" json:"status_msg,omitempty"`     // 状态描述
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProductResp) Reset() {
	*x = DeleteProductResp{}
	mi := &file_product_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProductResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProductResp) ProtoMessage() {}

func (x *DeleteProductResp) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProductResp.ProtoReflect.Descriptor instead.
func (*DeleteProductResp) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{18}
}

func (x *DeleteProductResp) GetStatusCode() uint32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *DeleteProductResp) GetStatusMsg() string {
	if x != nil {
		return x.StatusMsg
	}
	return ""
}

type RecommendProductReq_Paginator struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int64                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int64                  `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecommendProductReq_Paginator) Reset() {
	*x = RecommendProductReq_Paginator{}
	mi := &file_product_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecommendProductReq_Paginator) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecommendProductReq_Paginator) ProtoMessage() {}

func (x *RecommendProductReq_Paginator) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecommendProductReq_Paginator.ProtoReflect.Descriptor instead.
func (*RecommendProductReq_Paginator) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{4, 0}
}

func (x *RecommendProductReq_Paginator) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *RecommendProductReq_Paginator) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type QueryProductReq_Price struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Min           int64                  `protobuf:"varint,1,opt,name=min,proto3" json:"min,omitempty"` // 最低价格
	Max           int64                  `protobuf:"varint,2,opt,name=max,proto3" json:"max,omitempty"` // 最高价格
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryProductReq_Price) Reset() {
	*x = QueryProductReq_Price{}
	mi := &file_product_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryProductReq_Price) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryProductReq_Price) ProtoMessage() {}

func (x *QueryProductReq_Price) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryProductReq_Price.ProtoReflect.Descriptor instead.
func (*QueryProductReq_Price) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{5, 0}
}

func (x *QueryProductReq_Price) GetMin() int64 {
	if x != nil {
		return x.Min
	}
	return 0
}

func (x *QueryProductReq_Price) GetMax() int64 {
	if x != nil {
		return x.Max
	}
	return 0
}

type QueryProductReq_Paginator struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int64                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int64                  `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryProductReq_Paginator) Reset() {
	*x = QueryProductReq_Paginator{}
	mi := &file_product_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryProductReq_Paginator) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryProductReq_Paginator) ProtoMessage() {}

func (x *QueryProductReq_Paginator) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryProductReq_Paginator.ProtoReflect.Descriptor instead.
func (*QueryProductReq_Paginator) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{5, 1}
}

func (x *QueryProductReq_Paginator) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *QueryProductReq_Paginator) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

var File_product_proto protoreflect.FileDescriptor

const file_product_proto_rawDesc = "" +
	"\n" +
	"\rproduct.proto\x12\aproduct\"O\n" +
	"\x0fGetUploadURLReq\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12 \n" +
	"\vcontentType\x18\x02 \x01(\tR\vcontentType\"\x84\x02\n" +
	"\x10GetUploadURLResp\x12\x1c\n" +
	"\tuploadUrl\x18\x01 \x01(\tR\tuploadUrl\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12C\n" +
	"\bformData\x18\x03 \x03(\v2'.product.GetUploadURLResp.FormDataEntryR\bformData\x12\x1f\n" +
	"\vstatus_code\x18\x04 \x01(\rR\n" +
	"statusCode\x12\x1d\n" +
	"\n" +
	"status_msg\x18\x05 \x01(\tR\tstatusMsg\x1a;\n" +
	"\rFormDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"?\n" +
	"\x0fListProductsReq\x12\x16\n" +
	"\x06cursor\x18\x01 \x01(\x03R\x06cursor\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x03R\x05limit\"\xba\x01\n" +
	"\x10ListProductsResp\x12,\n" +
	"\bproducts\x18\x01 \x03(\v2\x10.product.ProductR\bproducts\x12\x1e\n" +
	"\n" +
	"nextCursor\x18\x02 \x01(\x03R\n" +
	"nextCursor\x12\x18\n" +
	"\ahasMore\x18\x03 \x01(\bR\ahasMore\x12\x1f\n" +
	"\vstatus_code\x18\x04 \x01(\rR\n" +
	"statusCode\x12\x1d\n" +
	"\n" +
	"status_msg\x18\x05 \x01(\tR\tstatusMsg\"\xcc\x01\n" +
	"\x13RecommendProductReq\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x05R\x06userId\x12D\n" +
	"\tpaginator\x18\x02 \x01(\v2&.product.RecommendProductReq.PaginatorR\tpaginator\x12\x1a\n" +
	"\bcategory\x18\x03 \x03(\tR\bcategory\x1a;\n" +
	"\tPaginator\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x03R\x04page\x12\x1a\n" +
	"\bpageSize\x18\x02 \x01(\x03R\bpageSize\"\xe1\x02\n" +
	"\x0fQueryProductReq\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03new\x18\x02 \x01(\bR\x03new\x12\x10\n" +
	"\x03hot\x18\x03 \x01(\bR\x03hot\x12\x18\n" +
	"\akeyword\x18\x04 \x01(\tR\akeyword\x12\x1a\n" +
	"\bcategory\x18\x05 \x03(\tR\bcategory\x124\n" +
	"\x05price\x18\x06 \x01(\v2\x1e.product.QueryProductReq.PriceR\x05price\x12@\n" +
	"\tpaginator\x18\a \x01(\v2\".product.QueryProductReq.PaginatorR\tpaginator\x1a+\n" +
	"\x05Price\x12\x10\n" +
	"\x03min\x18\x01 \x01(\x03R\x03min\x12\x10\n" +
	"\x03max\x18\x02 \x01(\x03R\x03max\x1a;\n" +
	"\tPaginator\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x03R\x04page\x12\x1a\n" +
	"\bpageSize\x18\x02 \x01(\x03R\bpageSize\"\xaa\x02\n" +
	"\aProduct\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x18\n" +
	"\apicture\x18\x04 \x01(\tR\apicture\x12\x14\n" +
	"\x05price\x18\x05 \x01(\x03R\x05price\x12\x14\n" +
	"\x05stock\x18\x06 \x01(\x03R\x05stock\x12\x12\n" +
	"\x04sold\x18\a \x01(\x03R\x04sold\x12\x1e\n" +
	"\n" +
	"categories\x18\b \x03(\tR\n" +
	"categories\x12\x1b\n" +
	"\tcrated_at\x18\t \x01(\tR\bcratedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\tR\tupdatedAt\x12#\n" +
	"\rthumbnail_url\x18\v \x01(\tR\fthumbnailUrl\"#\n" +
	"\x11IsExistProductReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"j\n" +
	"\x12IsExistProductResp\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\rR\n" +
	"statusCode\x12\x1d\n" +
	"\n" +
	"status_msg\x18\x02 \x01(\tR\tstatusMsg\x12\x14\n" +
	"\x05exist\x18\x03 \x01(\bR\x05exist\"C\n" +
	"\x11GetAllProductsReq\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x03R\x04page\x12\x1a\n" +
	"\bpageSize\x18\x02 \x01(\x03R\bpageSize\"\xc8\x01\n" +
	"\x12GetAllProductsResp\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\rR\n" +
	"statusCode\x12\x1d\n" +
	"\n" +
	"status_msg\x18\x02 \x01(\tR\tstatusMsg\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x03R\x05total\x12,\n" +
	"\bproducts\x18\x04 \x03(\v2\x10.product.ProductR\bproducts\x12\x12\n" +
	"\x04page\x18\x05 \x01(\x03R\x04page\x12\x1a\n" +
	"\bpageSize\x18\x06 \x01(\x03R\bpageSize\"8\n" +
	"\rGetProductReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x05R\x06userId\"|\n" +
	"\x0eGetProductResp\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\rR\n" +
	"statusCode\x12\x1d\n" +
	"\n" +
	"status_msg\x18\x02 \x01(\tR\tstatusMsg\x12*\n" +
	"\aproduct\x18\x03 \x01(\v2\x10.product.ProductR\aproduct\"\xae\x01\n" +
	"\x10CreateProductReq\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x18\n" +
	"\apicture\x18\x03 \x01(\fR\apicture\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x03R\x05price\x12\x14\n" +
	"\x05stock\x18\x05 \x01(\x03R\x05stock\x12\x1e\n" +
	"\n" +
	"categories\x18\x06 \x03(\tR\n" +
	"categories\"r\n" +
	"\x11CreateProductResp\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\rR\n" +
	"statusCode\x12\x1d\n" +
	"\n" +
	"status_msg\x18\x02 \x01(\tR\tstatusMsg\x12\x1d\n" +
	"\n" +
	"product_id\x18\x03 \x01(\x03R\tproductId\"\xbe\x01\n" +
	"\x10UpdateProductReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x18\n" +
	"\apicture\x18\x04 \x01(\fR\apicture\x12\x14\n" +
	"\x05price\x18\x05 \x01(\x03R\x05price\x12\x14\n" +
	"\x05stock\x18\x06 \x01(\x03R\x05stock\x12\x1e\n" +
	"\n" +
	"categories\x18\b \x03(\tR\n" +
	"categories\"c\n" +
	"\x11UpdateProductResp\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\rR\n" +
	"statusCode\x12\x1d\n" +
	"\n" +
	"status_msg\x18\x02 \x01(\tR\tstatusMsg\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\x03R\x02id\"\"\n" +
	"\x10DeleteProductReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"S\n" +
	"\x11DeleteProductResp\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\rR\n" +
	"statusCode\x12\x1d\n" +
	"\n" +
	"status_msg\x18\x02 \x01(\tR\tstatusMsg2\xf3\x05\n" +
	"\x15ProductCatalogService\x12?\n" +
	"\n" +
	"GetProduct\x12\x16.product.GetProductReq\x1a\x17.product.GetProductResp\"\x00\x12H\n" +
	"\rCreateProduct\x12\x19.product.CreateProductReq\x1a\x1a.product.CreateProductResp\"\x00\x12H\n" +
	"\rUpdateProduct\x12\x19.product.UpdateProductReq\x1a\x1a.product.UpdateProductResp\"\x00\x12H\n" +
	"\rDeleteProduct\x12\x19.product.DeleteProductReq\x1a\x1a.product.DeleteProductResp\"\x00\x12J\n" +
	"\rGetAllProduct\x12\x1a.product.GetAllProductsReq\x1a\x1b.product.GetAllProductsResp\"\x00\x12K\n" +
	"\x0eIsExistProduct\x12\x1a.product.IsExistProductReq\x1a\x1b.product.IsExistProductResp\"\x00\x12G\n" +
	"\fQueryProduct\x12\x18.product.QueryProductReq\x1a\x1b.product.GetAllProductsResp\"\x00\x12O\n" +
	"\x10RecommendProduct\x12\x1c.product.RecommendProductReq\x1a\x1b.product.GetAllProductsResp\"\x00\x12C\n" +
	"\fGetUploadURL\x12\x18.product.GetUploadURLReq\x1a\x19.product.GetUploadURLResp\x12C\n" +
	"\fListProducts\x12\x18.product.ListProductsReq\x1a\x19.product.ListProductsRespB\vZ\t./productb\x06proto3"

var (
	file_product_proto_rawDescOnce sync.Once
	file_product_proto_rawDescData []byte
)

func file_product_proto_rawDescGZIP() []byte {
	file_product_proto_rawDescOnce.Do(func() {
		file_product_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_product_proto_rawDesc), len(file_product_proto_rawDesc)))
	})
	return file_product_proto_rawDescData
}

var file_product_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_product_proto_goTypes = []any{
	(*GetUploadURLReq)(nil),               // 0: product.GetUploadURLReq
	(*GetUploadURLResp)(nil),              // 1: product.GetUploadURLResp
	(*ListProductsReq)(nil),               // 2: product.ListProductsReq
	(*ListProductsResp)(nil),              // 3: product.ListProductsResp
	(*RecommendProductReq)(nil),           // 4: product.RecommendProductReq
	(*QueryProductReq)(nil),               // 5: product.QueryProductReq
	(*Product)(nil),                       // 6: product.Product
	(*IsExistProductReq)(nil),             // 7: product.IsExistProductReq
	(*IsExistProductResp)(nil),            // 8: product.IsExistProductResp
	(*GetAllProductsReq)(nil),             // 9: product.GetAllProductsReq
	(*GetAllProductsResp)(nil),            // 10: product.GetAllProductsResp
	(*GetProductReq)(nil),                 // 11: product.GetProductReq
	(*GetProductResp)(nil),                // 12: product.GetProductResp
	(*CreateProductReq)(nil),              // 13: product.CreateProductReq
	(*CreateProductResp)(nil),             // 14: product.CreateProductResp
	(*UpdateProductReq)(nil),              // 15: product.UpdateProductReq
	(*UpdateProductResp)(nil),             // 16: product.UpdateProductResp
	(*DeleteProductReq)(nil),              // 17: product.DeleteProductReq
	(*DeleteProductResp)(nil),             // 18: product.DeleteProductResp
	nil,                                   // 19: product.GetUploadURLResp.FormDataEntry
	(*RecommendProductReq_Paginator)(nil), // 20: product.RecommendProductReq.Paginator
	(*QueryProductReq_Price)(nil),         // 21: product.QueryProductReq.Price
	(*QueryProductReq_Paginator)(nil),     // 22: product.QueryProductReq.Paginator
}
var file_product_proto_depIdxs = []int32{
	19, // 0: product.GetUploadURLResp.formData:type_name -> product.GetUploadURLResp.FormDataEntry
	6,  // 1: product.ListProductsResp.products:type_name -> product.Product
	20, // 2: product.RecommendProductReq.paginator:type_name -> product.RecommendProductReq.Paginator
	21, // 3: product.QueryProductReq.price:type_name -> product.QueryProductReq.Price
	22, // 4: product.QueryProductReq.paginator:type_name -> product.QueryProductReq.Paginator
	6,  // 5: product.GetAllProductsResp.products:type_name -> product.Product
	6,  // 6: product.GetProductResp.product:type_name -> product.Product
	11, // 7: product.ProductCatalogService.GetProduct:input_type -> product.GetProductReq
	13, // 8: product.ProductCatalogService.CreateProduct:input_type -> product.CreateProductReq
	15, // 9: product.ProductCatalogService.UpdateProduct:input_type -> product.UpdateProductReq
	17, // 10: product.ProductCatalogService.DeleteProduct:input_type -> product.DeleteProductReq
	9,  // 11: product.ProductCatalogService.GetAllProduct:input_type -> product.GetAllProductsReq
	7,  // 12: product.ProductCatalogService.IsExistProduct:input_type -> product.IsExistProductReq
	5,  // 13: product.ProductCatalogService.QueryProduct:input_type -> product.QueryProductReq
	4,  // 14: product.ProductCatalogService.RecommendProduct:input_type -> product.RecommendProductReq
	0,  // 15: product.ProductCatalogService.GetUploadURL:input_type -> product.GetUploadURLReq
	2,  // 16: product.ProductCatalogService.ListProducts:input_type -> product.ListProductsReq
	12, // 17: product.ProductCatalogService.GetProduct:output_type -> product.GetProductResp
	14, // 18: product.ProductCatalogService.CreateProduct:output_type -> product.CreateProductResp
	16, // 19: product.ProductCatalogService.UpdateProduct:output_type -> product.UpdateProductResp
	18, // 20: product.ProductCatalogService.DeleteProduct:output_type -> product.DeleteProductResp
	10, // 21: product.ProductCatalogService.GetAllProduct:output_type -> product.GetAllProductsResp
	8,  // 22: product.ProductCatalogService.IsExistProduct:output_type -> product.IsExistProductResp
	10, // 23: product.ProductCatalogService.QueryProduct:output_type -> product.GetAllProductsResp
	10, // 24: product.ProductCatalogService.RecommendProduct:output_type -> product.GetAllProductsResp
	1,  // 25: product.ProductCatalogService.GetUploadURL:output_type -> product.GetUploadURLResp
	3,  // 26: product.ProductCatalogService.ListProducts:output_type -> product.ListProductsResp
	17, // [17:27] is the sub-list for method output_type
	7,  // [7:17] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_product_proto_init() }
func file_product_proto_init() {
	if File_product_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_product_proto_rawDesc), len(file_product_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_product_proto_goTypes,
		DependencyIndexes: file_product_proto_depIdxs,
		MessageInfos:      file_product_proto_msgTypes,
	}.Build()
	File_product_proto = out.File
	file_product_proto_goTypes = nil
	file_product_proto_depIdxs = nil
}
