// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.1
// Source: order.proto

package server

import (
	"context"

	"github.com/falconfan123/Go-mall/services/order/internal/logic"
	"github.com/falconfan123/Go-mall/services/order/internal/svc"
	"github.com/falconfan123/Go-mall/services/order/pb"
)

type OrderServiceServer struct {
	svcCtx *svc.ServiceContext
	order.UnimplementedOrderServiceServer
}

func NewOrderServiceServer(svcCtx *svc.ServiceContext) *OrderServiceServer {
	return &OrderServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *OrderServiceServer) CreateOrder(ctx context.Context, in *order.CreateOrderRequest) (*order.OrderDetailResponse, error) {
	l := logic.NewCreateOrderLogic(ctx, s.svcCtx)
	return l.CreateOrder(in)
}
