// Code generated by MockGen. DO NOT EDIT.
// Source: services/payment/internal/domain/repository/payment_repository.go
//
// Generated by this command:
//
//	mockgen -source services/payment/internal/domain/repository/payment_repository.go -package testmock -destination services/payment/internal/testmock/mock_payment_repository.go
//

// Package testmock is a generated GoMock package.
package testmock

import (
	context "context"
	reflect "reflect"

	entity "github.com/falconfan123/Go-mall/services/payment/internal/domain/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockPaymentRepository is a mock of PaymentRepository interface.
type MockPaymentRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPaymentRepositoryMockRecorder
	isgomock struct{}
}

// MockPaymentRepositoryMockRecorder is the mock recorder for MockPaymentRepository.
type MockPaymentRepositoryMockRecorder struct {
	mock *MockPaymentRepository
}

// NewMockPaymentRepository creates a new mock instance.
func NewMockPaymentRepository(ctrl *gomock.Controller) *MockPaymentRepository {
	mock := &MockPaymentRepository{ctrl: ctrl}
	mock.recorder = &MockPaymentRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPaymentRepository) EXPECT() *MockPaymentRepositoryMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockPaymentRepository) Delete(ctx context.Context, paymentID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, paymentID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockPaymentRepositoryMockRecorder) Delete(ctx, paymentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockPaymentRepository)(nil).Delete), ctx, paymentID)
}

// FindExpired mocks base method.
func (m *MockPaymentRepository) FindExpired(ctx context.Context, limit int) ([]*entity.Payment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindExpired", ctx, limit)
	ret0, _ := ret[0].([]*entity.Payment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindExpired indicates an expected call of FindExpired.
func (mr *MockPaymentRepositoryMockRecorder) FindExpired(ctx, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindExpired", reflect.TypeOf((*MockPaymentRepository)(nil).FindExpired), ctx, limit)
}

// GetByID mocks base method.
func (m *MockPaymentRepository) GetByID(ctx context.Context, paymentID string) (*entity.Payment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, paymentID)
	ret0, _ := ret[0].(*entity.Payment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockPaymentRepositoryMockRecorder) GetByID(ctx, paymentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockPaymentRepository)(nil).GetByID), ctx, paymentID)
}

// GetByOrderID mocks base method.
func (m *MockPaymentRepository) GetByOrderID(ctx context.Context, orderID string) (*entity.Payment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByOrderID", ctx, orderID)
	ret0, _ := ret[0].(*entity.Payment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByOrderID indicates an expected call of GetByOrderID.
func (mr *MockPaymentRepositoryMockRecorder) GetByOrderID(ctx, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByOrderID", reflect.TypeOf((*MockPaymentRepository)(nil).GetByOrderID), ctx, orderID)
}

// GetByPreOrderID mocks base method.
func (m *MockPaymentRepository) GetByPreOrderID(ctx context.Context, preOrderID string) (*entity.Payment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByPreOrderID", ctx, preOrderID)
	ret0, _ := ret[0].(*entity.Payment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByPreOrderID indicates an expected call of GetByPreOrderID.
func (mr *MockPaymentRepositoryMockRecorder) GetByPreOrderID(ctx, preOrderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByPreOrderID", reflect.TypeOf((*MockPaymentRepository)(nil).GetByPreOrderID), ctx, preOrderID)
}

// ListByStatus mocks base method.
func (m *MockPaymentRepository) ListByStatus(ctx context.Context, status entity.PaymentStatus, page, pageSize int) ([]*entity.Payment, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByStatus", ctx, status, page, pageSize)
	ret0, _ := ret[0].([]*entity.Payment)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListByStatus indicates an expected call of ListByStatus.
func (mr *MockPaymentRepositoryMockRecorder) ListByStatus(ctx, status, page, pageSize any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByStatus", reflect.TypeOf((*MockPaymentRepository)(nil).ListByStatus), ctx, status, page, pageSize)
}

// ListByUserID mocks base method.
func (m *MockPaymentRepository) ListByUserID(ctx context.Context, userID int64, status *entity.PaymentStatus, page, pageSize int) ([]*entity.Payment, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByUserID", ctx, userID, status, page, pageSize)
	ret0, _ := ret[0].([]*entity.Payment)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListByUserID indicates an expected call of ListByUserID.
func (mr *MockPaymentRepositoryMockRecorder) ListByUserID(ctx, userID, status, page, pageSize any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByUserID", reflect.TypeOf((*MockPaymentRepository)(nil).ListByUserID), ctx, userID, status, page, pageSize)
}

// Save mocks base method.
func (m *MockPaymentRepository) Save(ctx context.Context, payment *entity.Payment) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, payment)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockPaymentRepositoryMockRecorder) Save(ctx, payment any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockPaymentRepository)(nil).Save), ctx, payment)
}

// Update mocks base method.
func (m *MockPaymentRepository) Update(ctx context.Context, payment *entity.Payment) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, payment)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockPaymentRepositoryMockRecorder) Update(ctx, payment any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockPaymentRepository)(nil).Update), ctx, payment)
}
