// Code generated by MockGen. DO NOT EDIT.
// Source: /Users/fan/.superset/projects/Go-mall/services/auths/internal/domain/repository/auth_repository.go
//
// Generated by this command:
//
//	mockgen -source /Users/fan/.superset/projects/Go-mall/services/auths/internal/domain/repository/auth_repository.go -package testmock -destination /Users/fan/.superset/projects/Go-mall/services/auths/internal/testmock/mock_token_repository.go
//

// Package testmock is a generated GoMock package.
package testmock

import (
	context "context"
	reflect "reflect"
	time "time"

	repository "github.com/falconfan123/Go-mall/services/auths/internal/domain/repository"
	gomock "go.uber.org/mock/gomock"
)

// MockTokenRepository is a mock of TokenRepository interface.
type MockTokenRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTokenRepositoryMockRecorder
	isgomock struct{}
}

// MockTokenRepositoryMockRecorder is the mock recorder for MockTokenRepository.
type MockTokenRepositoryMockRecorder struct {
	mock *MockTokenRepository
}

// NewMockTokenRepository creates a new mock instance.
func NewMockTokenRepository(ctrl *gomock.Controller) *MockTokenRepository {
	mock := &MockTokenRepository{ctrl: ctrl}
	mock.recorder = &MockTokenRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTokenRepository) EXPECT() *MockTokenRepositoryMockRecorder {
	return m.recorder
}

// GenerateToken mocks base method.
func (m *MockTokenRepository) GenerateToken(ctx context.Context, userID int64, clientIP string, expiry time.Duration) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateToken", ctx, userID, clientIP, expiry)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateToken indicates an expected call of GenerateToken.
func (mr *MockTokenRepositoryMockRecorder) GenerateToken(ctx, userID, clientIP, expiry any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateToken", reflect.TypeOf((*MockTokenRepository)(nil).GenerateToken), ctx, userID, clientIP, expiry)
}

// GetLogoutTime mocks base method.
func (m *MockTokenRepository) GetLogoutTime(ctx context.Context, userID int64) (*time.Time, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLogoutTime", ctx, userID)
	ret0, _ := ret[0].(*time.Time)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLogoutTime indicates an expected call of GetLogoutTime.
func (mr *MockTokenRepositoryMockRecorder) GetLogoutTime(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLogoutTime", reflect.TypeOf((*MockTokenRepository)(nil).GetLogoutTime), ctx, userID)
}

// ParseToken mocks base method.
func (m *MockTokenRepository) ParseToken(ctx context.Context, tokenString string) (*repository.TokenClaims, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParseToken", ctx, tokenString)
	ret0, _ := ret[0].(*repository.TokenClaims)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ParseToken indicates an expected call of ParseToken.
func (mr *MockTokenRepositoryMockRecorder) ParseToken(ctx, tokenString any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseToken", reflect.TypeOf((*MockTokenRepository)(nil).ParseToken), ctx, tokenString)
}

// SetLogoutTime mocks base method.
func (m *MockTokenRepository) SetLogoutTime(ctx context.Context, userID int64, logoutTime time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetLogoutTime", ctx, userID, logoutTime)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetLogoutTime indicates an expected call of SetLogoutTime.
func (mr *MockTokenRepositoryMockRecorder) SetLogoutTime(ctx, userID, logoutTime any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetLogoutTime", reflect.TypeOf((*MockTokenRepository)(nil).SetLogoutTime), ctx, userID, logoutTime)
}

// ValidateToken mocks base method.
func (m *MockTokenRepository) ValidateToken(ctx context.Context, tokenString, clientIP string) (*repository.TokenClaims, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateToken", ctx, tokenString, clientIP)
	ret0, _ := ret[0].(*repository.TokenClaims)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateToken indicates an expected call of ValidateToken.
func (mr *MockTokenRepositoryMockRecorder) ValidateToken(ctx, tokenString, clientIP any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateToken", reflect.TypeOf((*MockTokenRepository)(nil).ValidateToken), ctx, tokenString, clientIP)
}
