# 详细配置见：go-zero@v1.7.6\zrpc\config.go
Name: inventory.rpc
ListenOn: 0.0.0.0:10007 # 端口见接口文档
Mode: pro
Timeout: 5000

# 服务发现
Consul:
  Host: ${CONSUL_HOST}
  Key: inventory.rpc # 与服务名称保持一致
  Meta:
    Protocol: grpc
  Tag:
    - grpc

PostgresConfig:
  datasource: ${POSTGRES_DATA_SOURCE}

Log:
  ServiceName: inventory-rpc
  Mode: console
  Encoding: json
  Stat: false

# 指标监控配置
DevServer:
  Enabled: true
  Host: 0.0.0.0
  Port: 11007
  EnablePprof: false

# 链路追踪
Telemetry:
  Name: inventory.rpc # 与服务名称保持一致
  Endpoint: ${TRACES_ENDPOINT}
  Batcher: zipkin
  Sampler: 0.1 # 采样率，1.0表示全部采集, 0.1表示10%


RedisConf:
  Host: ${REDIS_HOST}
  Pass: ${REDIS_PASSWORD}
  Tls: false

