Name: inventory.rpc
ListenOn: 0.0.0.0:10007
Mode: dev

# 服务发现
Consul:
  Host: localhost:8500
  Key: inventory.rpc
  Meta:
    Protocol: grpc

Telemetry:
  Name: inventory.rpc
  Endpoint: http://localhost:14268/api/traces
  Batcher: zipkin
  Sampler: 1.0

Log:
  ServiceName: inventory-rpc
  Mode: console
  Encoding: json
  Stat: false

PostgresConfig:
  datasource: postgres://root:fht3825099@localhost:5432/mall?sslmode=disable

RedisConf:
  Host: localhost:6379
  Pass: ""
  Tls: false

# Prometheus 监控暴露
Prometheus:
  Host: 0.0.0.0
  Port: 9107
  Path: /metrics

