// Code generated by MockGen. DO NOT EDIT.
// Source: /Users/fan/.superset/projects/Go-mall/services/product/internal/domain/repository/product_repository.go
//
// Generated by this command:
//
//	mockgen -source /Users/fan/.superset/projects/Go-mall/services/product/internal/domain/repository/product_repository.go -package testmock -destination /Users/fan/.superset/projects/Go-mall/services/product/internal/testmock/mock_product_repository.go
//

// Package testmock is a generated GoMock package.
package testmock

import (
	context "context"
	reflect "reflect"

	aggregate "github.com/falconfan123/Go-mall/services/product/internal/domain/aggregate"
	gomock "go.uber.org/mock/gomock"
)

// MockProductRepository is a mock of ProductRepository interface.
type MockProductRepository struct {
	ctrl     *gomock.Controller
	recorder *MockProductRepositoryMockRecorder
	isgomock struct{}
}

// MockProductRepositoryMockRecorder is the mock recorder for MockProductRepository.
type MockProductRepositoryMockRecorder struct {
	mock *MockProductRepository
}

// NewMockProductRepository creates a new mock instance.
func NewMockProductRepository(ctrl *gomock.Controller) *MockProductRepository {
	mock := &MockProductRepository{ctrl: ctrl}
	mock.recorder = &MockProductRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProductRepository) EXPECT() *MockProductRepositoryMockRecorder {
	return m.recorder
}

// BatchGetByIDs mocks base method.
func (m *MockProductRepository) BatchGetByIDs(ctx context.Context, ids []int64) ([]*aggregate.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchGetByIDs", ctx, ids)
	ret0, _ := ret[0].([]*aggregate.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BatchGetByIDs indicates an expected call of BatchGetByIDs.
func (mr *MockProductRepositoryMockRecorder) BatchGetByIDs(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchGetByIDs", reflect.TypeOf((*MockProductRepository)(nil).BatchGetByIDs), ctx, ids)
}

// DecreaseStock mocks base method.
func (m *MockProductRepository) DecreaseStock(ctx context.Context, productID, quantity int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DecreaseStock", ctx, productID, quantity)
	ret0, _ := ret[0].(error)
	return ret0
}

// DecreaseStock indicates an expected call of DecreaseStock.
func (mr *MockProductRepositoryMockRecorder) DecreaseStock(ctx, productID, quantity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DecreaseStock", reflect.TypeOf((*MockProductRepository)(nil).DecreaseStock), ctx, productID, quantity)
}

// Delete mocks base method.
func (m *MockProductRepository) Delete(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockProductRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockProductRepository)(nil).Delete), ctx, id)
}

// GetByID mocks base method.
func (m *MockProductRepository) GetByID(ctx context.Context, id int64) (*aggregate.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*aggregate.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockProductRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockProductRepository)(nil).GetByID), ctx, id)
}

// IncreaseStock mocks base method.
func (m *MockProductRepository) IncreaseStock(ctx context.Context, productID, quantity int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncreaseStock", ctx, productID, quantity)
	ret0, _ := ret[0].(error)
	return ret0
}

// IncreaseStock indicates an expected call of IncreaseStock.
func (mr *MockProductRepositoryMockRecorder) IncreaseStock(ctx, productID, quantity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncreaseStock", reflect.TypeOf((*MockProductRepository)(nil).IncreaseStock), ctx, productID, quantity)
}

// List mocks base method.
func (m *MockProductRepository) List(ctx context.Context, page, pageSize int, categoryID *int64, keyword *string) ([]*aggregate.Product, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, page, pageSize, categoryID, keyword)
	ret0, _ := ret[0].([]*aggregate.Product)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockProductRepositoryMockRecorder) List(ctx, page, pageSize, categoryID, keyword any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockProductRepository)(nil).List), ctx, page, pageSize, categoryID, keyword)
}

// Save mocks base method.
func (m *MockProductRepository) Save(ctx context.Context, product *aggregate.Product) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, product)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockProductRepositoryMockRecorder) Save(ctx, product any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockProductRepository)(nil).Save), ctx, product)
}
