// Code generated by MockGen. DO NOT EDIT.
// Source: services/product/internal/application/event/event_publisher.go
//
// Generated by this command:
//
//	mockgen -source services/product/internal/application/event/event_publisher.go -package testmock -destination services/product/internal/testmock/mock_event_publisher.go
//

// Package testmock is a generated GoMock package.
package testmock

import (
	reflect "reflect"

	event "github.com/falconfan123/Go-mall/services/product/internal/domain/event"
	gomock "go.uber.org/mock/gomock"
)

// MockProductEventPublisher is a mock of ProductEventPublisher interface.
type MockProductEventPublisher struct {
	ctrl     *gomock.Controller
	recorder *MockProductEventPublisherMockRecorder
	isgomock struct{}
}

// MockProductEventPublisherMockRecorder is the mock recorder for MockProductEventPublisher.
type MockProductEventPublisherMockRecorder struct {
	mock *MockProductEventPublisher
}

// NewMockProductEventPublisher creates a new mock instance.
func NewMockProductEventPublisher(ctrl *gomock.Controller) *MockProductEventPublisher {
	mock := &MockProductEventPublisher{ctrl: ctrl}
	mock.recorder = &MockProductEventPublisherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProductEventPublisher) EXPECT() *MockProductEventPublisherMockRecorder {
	return m.recorder
}

// PublishProductCreated mocks base method.
func (m *MockProductEventPublisher) PublishProductCreated(evt *event.ProductCreatedEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishProductCreated", evt)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishProductCreated indicates an expected call of PublishProductCreated.
func (mr *MockProductEventPublisherMockRecorder) PublishProductCreated(evt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishProductCreated", reflect.TypeOf((*MockProductEventPublisher)(nil).PublishProductCreated), evt)
}

// PublishProductDeleted mocks base method.
func (m *MockProductEventPublisher) PublishProductDeleted(evt *event.ProductDeletedEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishProductDeleted", evt)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishProductDeleted indicates an expected call of PublishProductDeleted.
func (mr *MockProductEventPublisherMockRecorder) PublishProductDeleted(evt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishProductDeleted", reflect.TypeOf((*MockProductEventPublisher)(nil).PublishProductDeleted), evt)
}

// PublishProductStockChanged mocks base method.
func (m *MockProductEventPublisher) PublishProductStockChanged(evt *event.ProductStockChangedEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishProductStockChanged", evt)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishProductStockChanged indicates an expected call of PublishProductStockChanged.
func (mr *MockProductEventPublisherMockRecorder) PublishProductStockChanged(evt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishProductStockChanged", reflect.TypeOf((*MockProductEventPublisher)(nil).PublishProductStockChanged), evt)
}

// PublishProductUpdated mocks base method.
func (m *MockProductEventPublisher) PublishProductUpdated(evt *event.ProductUpdatedEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishProductUpdated", evt)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishProductUpdated indicates an expected call of PublishProductUpdated.
func (mr *MockProductEventPublisherMockRecorder) PublishProductUpdated(evt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishProductUpdated", reflect.TypeOf((*MockProductEventPublisher)(nil).PublishProductUpdated), evt)
}
