// Code generated by MockGen. DO NOT EDIT.
// Source: /Users/fan/.superset/projects/Go-mall/services/checkout/internal/domain/repository/checkout_repository.go
//
// Generated by this command:
//
//	mockgen -source /Users/fan/.superset/projects/Go-mall/services/checkout/internal/domain/repository/checkout_repository.go -package testmock -destination /Users/fan/.superset/projects/Go-mall/services/checkout/internal/testmock/mock_checkout_repository.go
//

// Package testmock is a generated GoMock package.
package testmock

import (
	context "context"
	reflect "reflect"

	entity "github.com/falconfan123/Go-mall/services/checkout/internal/domain/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockCheckoutRepository is a mock of CheckoutRepository interface.
type MockCheckoutRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCheckoutRepositoryMockRecorder
	isgomock struct{}
}

// MockCheckoutRepositoryMockRecorder is the mock recorder for MockCheckoutRepository.
type MockCheckoutRepositoryMockRecorder struct {
	mock *MockCheckoutRepository
}

// NewMockCheckoutRepository creates a new mock instance.
func NewMockCheckoutRepository(ctrl *gomock.Controller) *MockCheckoutRepository {
	mock := &MockCheckoutRepository{ctrl: ctrl}
	mock.recorder = &MockCheckoutRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCheckoutRepository) EXPECT() *MockCheckoutRepositoryMockRecorder {
	return m.recorder
}

// DecreaseStock mocks base method.
func (m *MockCheckoutRepository) DecreaseStock(ctx context.Context, items []*entity.CheckoutItem) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DecreaseStock", ctx, items)
	ret0, _ := ret[0].(error)
	return ret0
}

// DecreaseStock indicates an expected call of DecreaseStock.
func (mr *MockCheckoutRepositoryMockRecorder) DecreaseStock(ctx, items any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DecreaseStock", reflect.TypeOf((*MockCheckoutRepository)(nil).DecreaseStock), ctx, items)
}

// Delete mocks base method.
func (m *MockCheckoutRepository) Delete(ctx context.Context, preOrderID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, preOrderID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockCheckoutRepositoryMockRecorder) Delete(ctx, preOrderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockCheckoutRepository)(nil).Delete), ctx, preOrderID)
}

// FindExpired mocks base method.
func (m *MockCheckoutRepository) FindExpired(ctx context.Context, limit int) ([]*entity.Checkout, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindExpired", ctx, limit)
	ret0, _ := ret[0].([]*entity.Checkout)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindExpired indicates an expected call of FindExpired.
func (mr *MockCheckoutRepositoryMockRecorder) FindExpired(ctx, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindExpired", reflect.TypeOf((*MockCheckoutRepository)(nil).FindExpired), ctx, limit)
}

// GetByID mocks base method.
func (m *MockCheckoutRepository) GetByID(ctx context.Context, preOrderID string) (*entity.Checkout, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, preOrderID)
	ret0, _ := ret[0].(*entity.Checkout)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockCheckoutRepositoryMockRecorder) GetByID(ctx, preOrderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockCheckoutRepository)(nil).GetByID), ctx, preOrderID)
}

// GetByUserID mocks base method.
func (m *MockCheckoutRepository) GetByUserID(ctx context.Context, userID int64) ([]*entity.Checkout, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUserID", ctx, userID)
	ret0, _ := ret[0].([]*entity.Checkout)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUserID indicates an expected call of GetByUserID.
func (mr *MockCheckoutRepositoryMockRecorder) GetByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUserID", reflect.TypeOf((*MockCheckoutRepository)(nil).GetByUserID), ctx, userID)
}

// IncreaseStock mocks base method.
func (m *MockCheckoutRepository) IncreaseStock(ctx context.Context, items []*entity.CheckoutItem) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncreaseStock", ctx, items)
	ret0, _ := ret[0].(error)
	return ret0
}

// IncreaseStock indicates an expected call of IncreaseStock.
func (mr *MockCheckoutRepositoryMockRecorder) IncreaseStock(ctx, items any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncreaseStock", reflect.TypeOf((*MockCheckoutRepository)(nil).IncreaseStock), ctx, items)
}

// ListByUserID mocks base method.
func (m *MockCheckoutRepository) ListByUserID(ctx context.Context, userID int64, page, pageSize int) ([]*entity.Checkout, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByUserID", ctx, userID, page, pageSize)
	ret0, _ := ret[0].([]*entity.Checkout)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListByUserID indicates an expected call of ListByUserID.
func (mr *MockCheckoutRepositoryMockRecorder) ListByUserID(ctx, userID, page, pageSize any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByUserID", reflect.TypeOf((*MockCheckoutRepository)(nil).ListByUserID), ctx, userID, page, pageSize)
}

// Save mocks base method.
func (m *MockCheckoutRepository) Save(ctx context.Context, checkout *entity.Checkout) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, checkout)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockCheckoutRepositoryMockRecorder) Save(ctx, checkout any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockCheckoutRepository)(nil).Save), ctx, checkout)
}

// Update mocks base method.
func (m *MockCheckoutRepository) Update(ctx context.Context, checkout *entity.Checkout) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, checkout)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockCheckoutRepositoryMockRecorder) Update(ctx, checkout any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockCheckoutRepository)(nil).Update), ctx, checkout)
}
