// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: payment.proto

package payment

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PaymentStatus int32

const (
	PaymentStatus_PAYMENT_STATUS_UNSPECIFIED    PaymentStatus = 0 // 未指定或默认状态
	PaymentStatus_PAYMENT_STATUS_UNPAID         PaymentStatus = 1 // 创建支付单后，支付尚未完成
	PaymentStatus_PAYMENT_STATUS_PAID           PaymentStatus = 2 // 第三方支付成功回调，支付已完成
	PaymentStatus_PAYMENT_STATUS_FAILED         PaymentStatus = 3 // 支付接口返回错误，支付失败（如余额不足、银行卡限额）
	PaymentStatus_PAYMENT_STATUS_FULLY_REFUNDED PaymentStatus = 4 // 全额退款成功，订单金额全部退回
	PaymentStatus_PAYMENT_STATUS_EXPIRED        PaymentStatus = 5 // 支付链接超时未操作，支付单失效
)

// Enum value maps for PaymentStatus.
var (
	PaymentStatus_name = map[int32]string{
		0: "PAYMENT_STATUS_UNSPECIFIED",
		1: "PAYMENT_STATUS_UNPAID",
		2: "PAYMENT_STATUS_PAID",
		3: "PAYMENT_STATUS_FAILED",
		4: "PAYMENT_STATUS_FULLY_REFUNDED",
		5: "PAYMENT_STATUS_EXPIRED",
	}
	PaymentStatus_value = map[string]int32{
		"PAYMENT_STATUS_UNSPECIFIED":    0,
		"PAYMENT_STATUS_UNPAID":         1,
		"PAYMENT_STATUS_PAID":           2,
		"PAYMENT_STATUS_FAILED":         3,
		"PAYMENT_STATUS_FULLY_REFUNDED": 4,
		"PAYMENT_STATUS_EXPIRED":        5,
	}
)

func (x PaymentStatus) Enum() *PaymentStatus {
	p := new(PaymentStatus)
	*p = x
	return p
}

func (x PaymentStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PaymentStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_payment_proto_enumTypes[0].Descriptor()
}

func (PaymentStatus) Type() protoreflect.EnumType {
	return &file_payment_proto_enumTypes[0]
}

func (x PaymentStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PaymentStatus.Descriptor instead.
func (PaymentStatus) EnumDescriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{0}
}

type PaymentMethod int32

const (
	PaymentMethod_PAYMENT_METHOD_UNSPECIFIED PaymentMethod = 0 // 未指定或默认状态
	PaymentMethod_WECHAT_PAY                 PaymentMethod = 1 // 微信支付
	PaymentMethod_ALIPAY                     PaymentMethod = 2 // 支付宝支付
)

// Enum value maps for PaymentMethod.
var (
	PaymentMethod_name = map[int32]string{
		0: "PAYMENT_METHOD_UNSPECIFIED",
		1: "WECHAT_PAY",
		2: "ALIPAY",
	}
	PaymentMethod_value = map[string]int32{
		"PAYMENT_METHOD_UNSPECIFIED": 0,
		"WECHAT_PAY":                 1,
		"ALIPAY":                     2,
	}
)

func (x PaymentMethod) Enum() *PaymentMethod {
	p := new(PaymentMethod)
	*p = x
	return p
}

func (x PaymentMethod) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PaymentMethod) Descriptor() protoreflect.EnumDescriptor {
	return file_payment_proto_enumTypes[1].Descriptor()
}

func (PaymentMethod) Type() protoreflect.EnumType {
	return &file_payment_proto_enumTypes[1]
}

func (x PaymentMethod) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PaymentMethod.Descriptor instead.
func (PaymentMethod) EnumDescriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{1}
}

type PaymentItem struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PaymentId      string                 `protobuf:"bytes,1,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`                                         // 支付单ID（UUID）
	PreOrderId     string                 `protobuf:"bytes,2,opt,name=pre_order_id,json=preOrderId,proto3" json:"pre_order_id,omitempty"`                                    // 预订单ID（外键）
	OrderId        string                 `protobuf:"bytes,3,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`                                               // 成功关联的订单ID
	OriginalAmount int64                  `protobuf:"varint,4,opt,name=original_amount,json=originalAmount,proto3" json:"original_amount,omitempty"`                         // 原价（分）
	PaidAmount     int64                  `protobuf:"varint,5,opt,name=paid_amount,json=paidAmount,proto3" json:"paid_amount,omitempty"`                                     // 实付金额（分）
	PaymentMethod  PaymentMethod          `protobuf:"varint,6,opt,name=payment_method,json=paymentMethod,proto3,enum=payment.PaymentMethod" json:"payment_method,omitempty"` // 支付渠道（枚举类型）
	TransactionId  string                 `protobuf:"bytes,7,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`                             // 支付平台交易号
	PayUrl         string                 `protobuf:"bytes,8,opt,name=pay_url,json=payUrl,proto3" json:"pay_url,omitempty"`                                                  // 支付跳转链接
	ExpireTime     int64                  `protobuf:"varint,9,opt,name=expire_time,json=expireTime,proto3" json:"expire_time,omitempty"`                                     // 支付链接过期时间
	Status         PaymentStatus          `protobuf:"varint,10,opt,name=status,proto3,enum=payment.PaymentStatus" json:"status,omitempty"`                                   // 支付状态
	CreatedAt      int64                  `protobuf:"varint,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`                                       // 创建时间
	UpdatedAt      int64                  `protobuf:"varint,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`                                       // 更新时间
	PaidAt         int64                  `protobuf:"varint,13,opt,name=paid_at,json=paidAt,proto3" json:"paid_at,omitempty"`                                                // 支付成功时间
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PaymentItem) Reset() {
	*x = PaymentItem{}
	mi := &file_payment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentItem) ProtoMessage() {}

func (x *PaymentItem) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentItem.ProtoReflect.Descriptor instead.
func (*PaymentItem) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{0}
}

func (x *PaymentItem) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

func (x *PaymentItem) GetPreOrderId() string {
	if x != nil {
		return x.PreOrderId
	}
	return ""
}

func (x *PaymentItem) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *PaymentItem) GetOriginalAmount() int64 {
	if x != nil {
		return x.OriginalAmount
	}
	return 0
}

func (x *PaymentItem) GetPaidAmount() int64 {
	if x != nil {
		return x.PaidAmount
	}
	return 0
}

func (x *PaymentItem) GetPaymentMethod() PaymentMethod {
	if x != nil {
		return x.PaymentMethod
	}
	return PaymentMethod_PAYMENT_METHOD_UNSPECIFIED
}

func (x *PaymentItem) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *PaymentItem) GetPayUrl() string {
	if x != nil {
		return x.PayUrl
	}
	return ""
}

func (x *PaymentItem) GetExpireTime() int64 {
	if x != nil {
		return x.ExpireTime
	}
	return 0
}

func (x *PaymentItem) GetStatus() PaymentStatus {
	if x != nil {
		return x.Status
	}
	return PaymentStatus_PAYMENT_STATUS_UNSPECIFIED
}

func (x *PaymentItem) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *PaymentItem) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *PaymentItem) GetPaidAt() int64 {
	if x != nil {
		return x.PaidAt
	}
	return 0
}

type PaymentReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	OrderId       string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	PaymentMethod PaymentMethod          `protobuf:"varint,3,opt,name=payment_method,json=paymentMethod,proto3,enum=payment.PaymentMethod" json:"payment_method,omitempty"` // 支付渠道
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentReq) Reset() {
	*x = PaymentReq{}
	mi := &file_payment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentReq) ProtoMessage() {}

func (x *PaymentReq) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentReq.ProtoReflect.Descriptor instead.
func (*PaymentReq) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{1}
}

func (x *PaymentReq) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *PaymentReq) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *PaymentReq) GetPaymentMethod() PaymentMethod {
	if x != nil {
		return x.PaymentMethod
	}
	return PaymentMethod_PAYMENT_METHOD_UNSPECIFIED
}

type PaymentListReq struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	UserId        uint32                     `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PaymentMethod PaymentMethod              `protobuf:"varint,2,opt,name=payment_method,json=paymentMethod,proto3,enum=payment.PaymentMethod" json:"payment_method,omitempty"` // 支付渠道（可选过滤条件）
	Pagination    *PaymentListReq_Pagination `protobuf:"bytes,3,opt,name=pagination,proto3" json:"pagination,omitempty"`                                                        // 分页信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentListReq) Reset() {
	*x = PaymentListReq{}
	mi := &file_payment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentListReq) ProtoMessage() {}

func (x *PaymentListReq) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentListReq.ProtoReflect.Descriptor instead.
func (*PaymentListReq) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{2}
}

func (x *PaymentListReq) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *PaymentListReq) GetPaymentMethod() PaymentMethod {
	if x != nil {
		return x.PaymentMethod
	}
	return PaymentMethod_PAYMENT_METHOD_UNSPECIFIED
}

func (x *PaymentListReq) GetPagination() *PaymentListReq_Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type PaymentResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	StatusMsg     string                 `protobuf:"bytes,2,opt,name=status_msg,json=statusMsg,proto3" json:"status_msg,omitempty"`
	Payment       *PaymentItem           `protobuf:"bytes,3,opt,name=payment,proto3" json:"payment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentResp) Reset() {
	*x = PaymentResp{}
	mi := &file_payment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentResp) ProtoMessage() {}

func (x *PaymentResp) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentResp.ProtoReflect.Descriptor instead.
func (*PaymentResp) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{3}
}

func (x *PaymentResp) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *PaymentResp) GetStatusMsg() string {
	if x != nil {
		return x.StatusMsg
	}
	return ""
}

func (x *PaymentResp) GetPayment() *PaymentItem {
	if x != nil {
		return x.Payment
	}
	return nil
}

type PaymentListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	StatusMsg     string                 `protobuf:"bytes,2,opt,name=status_msg,json=statusMsg,proto3" json:"status_msg,omitempty"`
	Payments      []*PaymentItem         `protobuf:"bytes,3,rep,name=payments,proto3" json:"payments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentListResp) Reset() {
	*x = PaymentListResp{}
	mi := &file_payment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentListResp) ProtoMessage() {}

func (x *PaymentListResp) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentListResp.ProtoReflect.Descriptor instead.
func (*PaymentListResp) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{4}
}

func (x *PaymentListResp) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *PaymentListResp) GetStatusMsg() string {
	if x != nil {
		return x.StatusMsg
	}
	return ""
}

func (x *PaymentListResp) GetPayments() []*PaymentItem {
	if x != nil {
		return x.Payments
	}
	return nil
}

type PaymentListReq_Pagination struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`                         // 从1开始，默认值为1
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"` // 最大20，默认值为10
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentListReq_Pagination) Reset() {
	*x = PaymentListReq_Pagination{}
	mi := &file_payment_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentListReq_Pagination) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentListReq_Pagination) ProtoMessage() {}

func (x *PaymentListReq_Pagination) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentListReq_Pagination.ProtoReflect.Descriptor instead.
func (*PaymentListReq_Pagination) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{2, 0}
}

func (x *PaymentListReq_Pagination) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *PaymentListReq_Pagination) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

var File_payment_proto protoreflect.FileDescriptor

const file_payment_proto_rawDesc = "" +
	"\n" +
	"\rpayment.proto\x12\apayment\"\xda\x03\n" +
	"\vPaymentItem\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x01 \x01(\tR\tpaymentId\x12 \n" +
	"\fpre_order_id\x18\x02 \x01(\tR\n" +
	"preOrderId\x12\x19\n" +
	"\border_id\x18\x03 \x01(\tR\aorderId\x12'\n" +
	"\x0foriginal_amount\x18\x04 \x01(\x03R\x0eoriginalAmount\x12\x1f\n" +
	"\vpaid_amount\x18\x05 \x01(\x03R\n" +
	"paidAmount\x12=\n" +
	"\x0epayment_method\x18\x06 \x01(\x0e2\x16.payment.PaymentMethodR\rpaymentMethod\x12%\n" +
	"\x0etransaction_id\x18\a \x01(\tR\rtransactionId\x12\x17\n" +
	"\apay_url\x18\b \x01(\tR\x06payUrl\x12\x1f\n" +
	"\vexpire_time\x18\t \x01(\x03R\n" +
	"expireTime\x12.\n" +
	"\x06status\x18\n" +
	" \x01(\x0e2\x16.payment.PaymentStatusR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\v \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\f \x01(\x03R\tupdatedAt\x12\x17\n" +
	"\apaid_at\x18\r \x01(\x03R\x06paidAt\"\x7f\n" +
	"\n" +
	"PaymentReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\x12=\n" +
	"\x0epayment_method\x18\x03 \x01(\x0e2\x16.payment.PaymentMethodR\rpaymentMethod\"\xeb\x01\n" +
	"\x0ePaymentListReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\x12=\n" +
	"\x0epayment_method\x18\x02 \x01(\x0e2\x16.payment.PaymentMethodR\rpaymentMethod\x12B\n" +
	"\n" +
	"pagination\x18\x03 \x01(\v2\".payment.PaymentListReq.PaginationR\n" +
	"pagination\x1a=\n" +
	"\n" +
	"Pagination\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\"}\n" +
	"\vPaymentResp\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x1d\n" +
	"\n" +
	"status_msg\x18\x02 \x01(\tR\tstatusMsg\x12.\n" +
	"\apayment\x18\x03 \x01(\v2\x14.payment.PaymentItemR\apayment\"\x83\x01\n" +
	"\x0fPaymentListResp\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x1d\n" +
	"\n" +
	"status_msg\x18\x02 \x01(\tR\tstatusMsg\x120\n" +
	"\bpayments\x18\x03 \x03(\v2\x14.payment.PaymentItemR\bpayments*\xbd\x01\n" +
	"\rPaymentStatus\x12\x1e\n" +
	"\x1aPAYMENT_STATUS_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15PAYMENT_STATUS_UNPAID\x10\x01\x12\x17\n" +
	"\x13PAYMENT_STATUS_PAID\x10\x02\x12\x19\n" +
	"\x15PAYMENT_STATUS_FAILED\x10\x03\x12!\n" +
	"\x1dPAYMENT_STATUS_FULLY_REFUNDED\x10\x04\x12\x1a\n" +
	"\x16PAYMENT_STATUS_EXPIRED\x10\x05*K\n" +
	"\rPaymentMethod\x12\x1e\n" +
	"\x1aPAYMENT_METHOD_UNSPECIFIED\x10\x00\x12\x0e\n" +
	"\n" +
	"WECHAT_PAY\x10\x01\x12\n" +
	"\n" +
	"\x06ALIPAY\x10\x022\x88\x01\n" +
	"\aPayment\x12:\n" +
	"\rCreatePayment\x12\x13.payment.PaymentReq\x1a\x14.payment.PaymentResp\x12A\n" +
	"\fListPayments\x12\x17.payment.PaymentListReq\x1a\x18.payment.PaymentListRespB\vZ\t./paymentb\x06proto3"

var (
	file_payment_proto_rawDescOnce sync.Once
	file_payment_proto_rawDescData []byte
)

func file_payment_proto_rawDescGZIP() []byte {
	file_payment_proto_rawDescOnce.Do(func() {
		file_payment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_payment_proto_rawDesc), len(file_payment_proto_rawDesc)))
	})
	return file_payment_proto_rawDescData
}

var file_payment_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_payment_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_payment_proto_goTypes = []any{
	(PaymentStatus)(0),                // 0: payment.PaymentStatus
	(PaymentMethod)(0),                // 1: payment.PaymentMethod
	(*PaymentItem)(nil),               // 2: payment.PaymentItem
	(*PaymentReq)(nil),                // 3: payment.PaymentReq
	(*PaymentListReq)(nil),            // 4: payment.PaymentListReq
	(*PaymentResp)(nil),               // 5: payment.PaymentResp
	(*PaymentListResp)(nil),           // 6: payment.PaymentListResp
	(*PaymentListReq_Pagination)(nil), // 7: payment.PaymentListReq.Pagination
}
var file_payment_proto_depIdxs = []int32{
	1, // 0: payment.PaymentItem.payment_method:type_name -> payment.PaymentMethod
	0, // 1: payment.PaymentItem.status:type_name -> payment.PaymentStatus
	1, // 2: payment.PaymentReq.payment_method:type_name -> payment.PaymentMethod
	1, // 3: payment.PaymentListReq.payment_method:type_name -> payment.PaymentMethod
	7, // 4: payment.PaymentListReq.pagination:type_name -> payment.PaymentListReq.Pagination
	2, // 5: payment.PaymentResp.payment:type_name -> payment.PaymentItem
	2, // 6: payment.PaymentListResp.payments:type_name -> payment.PaymentItem
	3, // 7: payment.Payment.CreatePayment:input_type -> payment.PaymentReq
	4, // 8: payment.Payment.ListPayments:input_type -> payment.PaymentListReq
	5, // 9: payment.Payment.CreatePayment:output_type -> payment.PaymentResp
	6, // 10: payment.Payment.ListPayments:output_type -> payment.PaymentListResp
	9, // [9:11] is the sub-list for method output_type
	7, // [7:9] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_payment_proto_init() }
func file_payment_proto_init() {
	if File_payment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_payment_proto_rawDesc), len(file_payment_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_payment_proto_goTypes,
		DependencyIndexes: file_payment_proto_depIdxs,
		EnumInfos:         file_payment_proto_enumTypes,
		MessageInfos:      file_payment_proto_msgTypes,
	}.Build()
	File_payment_proto = out.File
	file_payment_proto_goTypes = nil
	file_payment_proto_depIdxs = nil
}
