// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.1

package user_address

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	userAddressesFieldNames          = builder.RawFieldNames(&UserAddresses{}, true)
	userAddressesRows                = strings.Join(userAddressesFieldNames, ",")
	userAddressesRowsExpectAutoSet   = strings.Join(stringx.Remove(userAddressesFieldNames, "address_id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	userAddressesRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(userAddressesFieldNames, "address_id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))
)

type (
	userAddressesModel interface {
		Insert(ctx context.Context, data *UserAddresses) (sql.Result, error)
		FindOne(ctx context.Context, addressId int64) (*UserAddresses, error)
		Update(ctx context.Context, data *UserAddresses) error
		Delete(ctx context.Context, addressId int64) error
	}

	defaultUserAddressesModel struct {
		conn  sqlx.SqlConn
		table string
	}

	UserAddresses struct {
		AddressId       int64          `db:"address_id"`
		UserId          int64          `db:"user_id"`
		RecipientName   string         `db:"recipient_name"`
		PhoneNumber     sql.NullString `db:"phone_number"`
		Province        sql.NullString `db:"province"`
		City            string         `db:"city"`
		DetailedAddress string         `db:"detailed_address"`
		IsDefault       bool           `db:"is_default"`
		CreatedAt       time.Time      `db:"created_at"`
		UpdatedAt       time.Time      `db:"updated_at"`
		DeletedAt       sql.NullTime   `db:"deleted_at"`
	}
)

func newUserAddressesModel(conn sqlx.SqlConn) *defaultUserAddressesModel {
	return &defaultUserAddressesModel{
		conn:  conn,
		table: "\"public\".\"user_address\"",
	}
}

func (m *defaultUserAddressesModel) Delete(ctx context.Context, addressId int64) error {
	query := fmt.Sprintf("delete from %s where address_id = $1", m.table)
	_, err := m.conn.ExecCtx(ctx, query, addressId)
	return err
}

func (m *defaultUserAddressesModel) FindOne(ctx context.Context, addressId int64) (*UserAddresses, error) {
	query := fmt.Sprintf("select %s from %s where address_id = $1 limit 1", userAddressesRows, m.table)
	var resp UserAddresses
	err := m.conn.QueryRowCtx(ctx, &resp, query, addressId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserAddressesModel) Insert(ctx context.Context, data *UserAddresses) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3, $4, $5, $6, $7, $8)", m.table, userAddressesRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.UserId, data.RecipientName, data.PhoneNumber, data.Province, data.City, data.DetailedAddress, data.IsDefault, data.DeletedAt)
	return ret, err
}

func (m *defaultUserAddressesModel) Update(ctx context.Context, data *UserAddresses) error {
	query := fmt.Sprintf("update %s set %s where address_id = $1", m.table, userAddressesRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.UserId, data.RecipientName, data.PhoneNumber, data.Province, data.City, data.DetailedAddress, data.IsDefault, data.DeletedAt, data.AddressId)
	return err
}
