Name: products.rpc
ListenOn: 0.0.0.0:10002
Mode: pro
# 服务发现
Etcd:
  Hosts:
    - ${ETCD_HOST}
  Key: products.rpc
InventoryRpc:
  Etcd:
    Hosts:
      - ${ETCD_HOST}
    Key: inventory.rpc
  NonBlock: true
  Timeout: 3000

PostgresConfig:
  datasource: ${POSTGRES_DATA_SOURCE}
  Conntimeout: 5

Log:
  ServiceName: "products-rpc"
  Mode: 'console'
  Encoding: "json"
  Stat: false

# 指标监控配置
DevServer:
  Enabled: true
  Host: 0.0.0.0
  Port: 11002
  EnablePprof: false

# 链路追踪
Telemetry:
  Name: products.rpc # 与服务名称保持一致
  Endpoint: ${TRACES_ENDPOINT}
  Batcher: zipkin
  Sampler: 0.1  # 采样率，1.0表示全部采集, 0.1表示10%

# Elasticsearch 配置
ElasticSearch:
  Addr: ${ELASTICSEARCH_HOST}

# Redis
RedisConf:
  Host: ${REDIS_HOST}
  Pass: ${REDIS_PASSWORD}
  Tls: false

# Gorse
GorseConfig:
  GorseAddr: ${GORSE_HOST}
  GorseApikey: ${GORSE_APIKEY}

Minio:
  Enabled: ${MINIO_ENABLED}
  Endpoint: ${MINIO_ENDPOINT}
  AccessKey: ${MINIO_ACCESS_KEY}
  SecretKey: ${MINIO_SECRET_KEY}
  Bucket: ${MINIO_BUCKET}
  UseSSL: false
