// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.1
// Source: activity.proto

package server

import (
	"context"

	"github.com/falconfan123/Go-mall/services/activity/internal/logic"
	"github.com/falconfan123/Go-mall/services/activity/internal/svc"
	"github.com/falconfan123/Go-mall/services/activity/pb"
)

type ActivityServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedActivityServer
}

func NewActivityServer(svcCtx *svc.ServiceContext) *ActivityServer {
	return &ActivityServer{
		svcCtx: svcCtx,
	}
}

// Token 获取下单动态路径
func (s *ActivityServer) Token(ctx context.Context, in *pb.TokenReq) (*pb.TokenResp, error) {
	l := logic.NewTokenLogic(ctx, s.svcCtx)
	// TODO: 从 ctx 中获取实际的用户 ID
	return l.Token(in, 1)
}
