// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.1

package product

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	productsFieldNames          = builder.RawFieldNames(&Products{}, true)
	productsRows                = strings.Join(productsFieldNames, ",")
	productsRowsExpectAutoSet   = strings.Join(stringx.Remove(productsFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	productsRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(productsFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))
)

type (
	productsModel interface {
		Insert(ctx context.Context, data *Products) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Products, error)
		Update(ctx context.Context, data *Products) error
		Delete(ctx context.Context, id int64) error
	}

	defaultProductsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Products struct {
		Id          int64          `db:"id"`
		Name        string         `db:"name"`
		Description sql.NullString `db:"description"`
		Picture     sql.NullString `db:"picture"`
		Price       int64          `db:"price"`
		Stock       int64          `db:"stock"`
		CreatedAt   time.Time      `db:"created_at"`
		UpdatedAt   time.Time      `db:"updated_at"`
	}
)

func newProductsModel(conn sqlx.SqlConn) *defaultProductsModel {
	return &defaultProductsModel{
		conn:  conn,
		table: `"public"."products"`,
	}
}

func (m *defaultProductsModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where id = $1", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultProductsModel) FindOne(ctx context.Context, id int64) (*Products, error) {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", productsRows, m.table)
	var resp Products
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultProductsModel) Insert(ctx context.Context, data *Products) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3, $4, $5)", m.table, productsRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Name, data.Description, data.Picture, data.Price, data.Stock)
	return ret, err
}

func (m *defaultProductsModel) Update(ctx context.Context, data *Products) error {
	query := fmt.Sprintf("update %s set %s where id = $1", m.table, productsRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Id, data.Name, data.Description, data.Picture, data.Price, data.Stock)
	return err
}

func (m *defaultProductsModel) tableName() string {
	return m.table
}
