// Code generated by MockGen. DO NOT EDIT.
// Source: services/coupons/internal/domain/repository/user_coupon_repository.go
//
// Generated by this command:
//
//	mockgen -source services/coupons/internal/domain/repository/user_coupon_repository.go -package testmock -destination services/coupons/internal/testmock/mock_user_coupon_repository.go
//

// Package testmock is a generated GoMock package.
package testmock

import (
	context "context"
	reflect "reflect"

	entity "github.com/falconfan123/Go-mall/services/coupons/internal/domain/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockUserCouponRepository is a mock of UserCouponRepository interface.
type MockUserCouponRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserCouponRepositoryMockRecorder
	isgomock struct{}
}

// MockUserCouponRepositoryMockRecorder is the mock recorder for MockUserCouponRepository.
type MockUserCouponRepositoryMockRecorder struct {
	mock *MockUserCouponRepository
}

// NewMockUserCouponRepository creates a new mock instance.
func NewMockUserCouponRepository(ctrl *gomock.Controller) *MockUserCouponRepository {
	mock := &MockUserCouponRepository{ctrl: ctrl}
	mock.recorder = &MockUserCouponRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserCouponRepository) EXPECT() *MockUserCouponRepositoryMockRecorder {
	return m.recorder
}

// CountByUserIDAndCouponID mocks base method.
func (m *MockUserCouponRepository) CountByUserIDAndCouponID(ctx context.Context, userID int64, couponID string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountByUserIDAndCouponID", ctx, userID, couponID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountByUserIDAndCouponID indicates an expected call of CountByUserIDAndCouponID.
func (mr *MockUserCouponRepositoryMockRecorder) CountByUserIDAndCouponID(ctx, userID, couponID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountByUserIDAndCouponID", reflect.TypeOf((*MockUserCouponRepository)(nil).CountByUserIDAndCouponID), ctx, userID, couponID)
}

// Delete mocks base method.
func (m *MockUserCouponRepository) Delete(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockUserCouponRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockUserCouponRepository)(nil).Delete), ctx, id)
}

// FindAvailableByUserID mocks base method.
func (m *MockUserCouponRepository) FindAvailableByUserID(ctx context.Context, userID, orderAmount int64) ([]*entity.UserCoupon, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAvailableByUserID", ctx, userID, orderAmount)
	ret0, _ := ret[0].([]*entity.UserCoupon)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAvailableByUserID indicates an expected call of FindAvailableByUserID.
func (mr *MockUserCouponRepositoryMockRecorder) FindAvailableByUserID(ctx, userID, orderAmount any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAvailableByUserID", reflect.TypeOf((*MockUserCouponRepository)(nil).FindAvailableByUserID), ctx, userID, orderAmount)
}

// GetByID mocks base method.
func (m *MockUserCouponRepository) GetByID(ctx context.Context, id int64) (*entity.UserCoupon, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*entity.UserCoupon)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockUserCouponRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockUserCouponRepository)(nil).GetByID), ctx, id)
}

// GetByUserIDAndCouponID mocks base method.
func (m *MockUserCouponRepository) GetByUserIDAndCouponID(ctx context.Context, userID int64, couponID string) (*entity.UserCoupon, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUserIDAndCouponID", ctx, userID, couponID)
	ret0, _ := ret[0].(*entity.UserCoupon)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUserIDAndCouponID indicates an expected call of GetByUserIDAndCouponID.
func (mr *MockUserCouponRepositoryMockRecorder) GetByUserIDAndCouponID(ctx, userID, couponID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUserIDAndCouponID", reflect.TypeOf((*MockUserCouponRepository)(nil).GetByUserIDAndCouponID), ctx, userID, couponID)
}

// ListByUserID mocks base method.
func (m *MockUserCouponRepository) ListByUserID(ctx context.Context, userID int64, status *entity.UserCouponStatus, page, pageSize int) ([]*entity.UserCoupon, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByUserID", ctx, userID, status, page, pageSize)
	ret0, _ := ret[0].([]*entity.UserCoupon)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListByUserID indicates an expected call of ListByUserID.
func (mr *MockUserCouponRepositoryMockRecorder) ListByUserID(ctx, userID, status, page, pageSize any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByUserID", reflect.TypeOf((*MockUserCouponRepository)(nil).ListByUserID), ctx, userID, status, page, pageSize)
}

// Save mocks base method.
func (m *MockUserCouponRepository) Save(ctx context.Context, userCoupon *entity.UserCoupon) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, userCoupon)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockUserCouponRepositoryMockRecorder) Save(ctx, userCoupon any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockUserCouponRepository)(nil).Save), ctx, userCoupon)
}

// Update mocks base method.
func (m *MockUserCouponRepository) Update(ctx context.Context, userCoupon *entity.UserCoupon) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, userCoupon)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockUserCouponRepositoryMockRecorder) Update(ctx, userCoupon any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockUserCouponRepository)(nil).Update), ctx, userCoupon)
}
