// Code generated by MockGen. DO NOT EDIT.
// Source: services/coupons/internal/domain/repository/coupon_repository.go
//
// Generated by this command:
//
//	mockgen -source services/coupons/internal/domain/repository/coupon_repository.go -package testmock -destination services/coupons/internal/testmock/mock_coupon_repository.go
//

// Package testmock is a generated GoMock package.
package testmock

import (
	context "context"
	reflect "reflect"

	aggregate "github.com/falconfan123/Go-mall/services/coupons/internal/domain/aggregate"
	gomock "go.uber.org/mock/gomock"
)

// MockCouponRepository is a mock of CouponRepository interface.
type MockCouponRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCouponRepositoryMockRecorder
	isgomock struct{}
}

// MockCouponRepositoryMockRecorder is the mock recorder for MockCouponRepository.
type MockCouponRepositoryMockRecorder struct {
	mock *MockCouponRepository
}

// NewMockCouponRepository creates a new mock instance.
func NewMockCouponRepository(ctrl *gomock.Controller) *MockCouponRepository {
	mock := &MockCouponRepository{ctrl: ctrl}
	mock.recorder = &MockCouponRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCouponRepository) EXPECT() *MockCouponRepositoryMockRecorder {
	return m.recorder
}

// DecreaseStock mocks base method.
func (m *MockCouponRepository) DecreaseStock(ctx context.Context, couponID string, count int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DecreaseStock", ctx, couponID, count)
	ret0, _ := ret[0].(error)
	return ret0
}

// DecreaseStock indicates an expected call of DecreaseStock.
func (mr *MockCouponRepositoryMockRecorder) DecreaseStock(ctx, couponID, count any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DecreaseStock", reflect.TypeOf((*MockCouponRepository)(nil).DecreaseStock), ctx, couponID, count)
}

// Delete mocks base method.
func (m *MockCouponRepository) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockCouponRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockCouponRepository)(nil).Delete), ctx, id)
}

// GetByID mocks base method.
func (m *MockCouponRepository) GetByID(ctx context.Context, id string) (*aggregate.Coupon, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*aggregate.Coupon)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockCouponRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockCouponRepository)(nil).GetByID), ctx, id)
}

// IncreaseStock mocks base method.
func (m *MockCouponRepository) IncreaseStock(ctx context.Context, couponID string, count int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncreaseStock", ctx, couponID, count)
	ret0, _ := ret[0].(error)
	return ret0
}

// IncreaseStock indicates an expected call of IncreaseStock.
func (mr *MockCouponRepositoryMockRecorder) IncreaseStock(ctx, couponID, count any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncreaseStock", reflect.TypeOf((*MockCouponRepository)(nil).IncreaseStock), ctx, couponID, count)
}

// List mocks base method.
func (m *MockCouponRepository) List(ctx context.Context, page, pageSize int) ([]*aggregate.Coupon, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, page, pageSize)
	ret0, _ := ret[0].([]*aggregate.Coupon)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockCouponRepositoryMockRecorder) List(ctx, page, pageSize any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockCouponRepository)(nil).List), ctx, page, pageSize)
}

// ListAvailable mocks base method.
func (m *MockCouponRepository) ListAvailable(ctx context.Context, page, pageSize int) ([]*aggregate.Coupon, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAvailable", ctx, page, pageSize)
	ret0, _ := ret[0].([]*aggregate.Coupon)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListAvailable indicates an expected call of ListAvailable.
func (mr *MockCouponRepositoryMockRecorder) ListAvailable(ctx, page, pageSize any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAvailable", reflect.TypeOf((*MockCouponRepository)(nil).ListAvailable), ctx, page, pageSize)
}

// Save mocks base method.
func (m *MockCouponRepository) Save(ctx context.Context, coupon *aggregate.Coupon) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, coupon)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockCouponRepositoryMockRecorder) Save(ctx, coupon any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockCouponRepository)(nil).Save), ctx, coupon)
}

// Update mocks base method.
func (m *MockCouponRepository) Update(ctx context.Context, coupon *aggregate.Coupon) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, coupon)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockCouponRepositoryMockRecorder) Update(ctx, coupon any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockCouponRepository)(nil).Update), ctx, coupon)
}
