// Code generated by goctl. DO NOT EDIT.
// Source: audit.proto

package auditclient

import (
	"context"

	"github.com/falconfan123/Go-mall/services/audit/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CreateAuditLogReq = pb.CreateAuditLogReq
	CreateAuditLogRes = pb.CreateAuditLogRes

	Audit interface {
		// CreateAuditLog 创建审计日志
		CreateAuditLog(ctx context.Context, in *CreateAuditLogReq, opts ...grpc.CallOption) (*CreateAuditLogRes, error)
	}

	defaultAudit struct {
		cli zrpc.Client
	}
)

func NewAudit(cli zrpc.Client) Audit {
	return &defaultAudit{
		cli: cli,
	}
}

// CreateAuditLog 创建审计日志
func (m *defaultAudit) CreateAuditLog(ctx context.Context, in *CreateAuditLogReq, opts ...grpc.CallOption) (*CreateAuditLogRes, error) {
	client := pb.NewAuditClient(m.cli.Conn())
	return client.CreateAuditLog(ctx, in, opts...)
}
