// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.1

package user

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	usersFieldNames          = builder.RawFieldNames(&Users{}, true)
	usersRows                = strings.Join(usersFieldNames, ",")
	usersRowsExpectAutoSet   = strings.Join(stringx.Remove(usersFieldNames, "user_id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	usersRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(usersFieldNames, "user_id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))
)

type (
	usersModel interface {
		Insert(ctx context.Context, data *Users) (sql.Result, error)
		FindOne(ctx context.Context, userId int64) (*Users, error)
		FindOneByEmail(ctx context.Context, email sql.NullString) (*Users, error)
		FindOneByUsername(ctx context.Context, username string) (*Users, error)
		Update(ctx context.Context, data *Users) error
		Delete(ctx context.Context, userId int64) error
	}

	defaultUsersModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Users struct {
		UserId       int64          `db:"user_id"`       // 主键，自增，用户 ID
		Username     sql.NullString `db:"username"`      // 用户名，可空
		Email        sql.NullString `db:"email"`         // 邮箱，唯一
		PasswordHash sql.NullString `db:"password_hash"` // 密码哈希值
		AvatarUrl    sql.NullString `db:"avatar_url"`    // 头像图片 URL
		CreatedAt    time.Time      `db:"created_at"`    // 创建时间
		UserDeleted  bool           `db:"user_deleted"`  // 用户是否已删除
		LogoutAt     sql.NullTime   `db:"logout_at"`     // 最近一次登出时间
		LoginAt      sql.NullTime   `db:"login_at"`      // 最近一次登录时间
		UpdatedAt    time.Time      `db:"updated_at"`    // 更新时间
	}
)

func newUsersModel(conn sqlx.SqlConn) *defaultUsersModel {
	return &defaultUsersModel{
		conn:  conn,
		table: "\"public\".\"users\"",
	}
}

func (m *defaultUsersModel) Delete(ctx context.Context, userId int64) error {
	query := fmt.Sprintf("delete from %s where user_id = $1", m.table)
	_, err := m.conn.ExecCtx(ctx, query, userId)
	return err
}

func (m *defaultUsersModel) FindOne(ctx context.Context, userId int64) (*Users, error) {
	query := fmt.Sprintf("select %s from %s where user_id = $1 limit 1", usersRows, m.table)
	var resp Users
	err := m.conn.QueryRowCtx(ctx, &resp, query, userId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUsersModel) FindOneByEmail(ctx context.Context, email sql.NullString) (*Users, error) {
	query := fmt.Sprintf("select %s from %s where email = $1 limit 1", usersRows, m.table)
	var resp Users
	err := m.conn.QueryRowCtx(ctx, &resp, query, email)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUsersModel) Insert(ctx context.Context, data *Users) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (%s)", m.table, usersRowsExpectAutoSet, usersRowsWithPlaceHolder)
	resp, err := m.conn.ExecCtx(ctx, query, data.UserId, data.Username, data.Email, data.PasswordHash, data.AvatarUrl, data.CreatedAt, data.UserDeleted, data.LogoutAt, data.LoginAt, data.UpdatedAt)
	return resp, err
}

func (m *defaultUsersModel) Update(ctx context.Context, data *Users) error {
	query := fmt.Sprintf("update %s set %s where user_id = $%d", m.table, usersRowsWithPlaceHolder, 11)
	_, err := m.conn.ExecCtx(ctx, query, data.Username, data.Email, data.PasswordHash, data.AvatarUrl, data.CreatedAt, data.UserDeleted, data.LogoutAt, data.LoginAt, data.UpdatedAt, data.UserId)
	return err
}
