// Code generated by goctl. DO NOT EDIT.
// Source: coupons.proto

package couponsclient

import (
	"context"

	"github.com/falconfan123/Go-mall/services/coupons/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CalculateCouponReq   = pb.CalculateCouponReq
	CalculateCouponResp  = pb.CalculateCouponResp
	ClaimCouponReq       = pb.ClaimCouponReq
	ClaimCouponResp      = pb.ClaimCouponResp
	Coupon               = pb.Coupon
	CouponUsage          = pb.CouponUsage
	EmptyResp            = pb.EmptyResp
	GetCouponReq         = pb.GetCouponReq
	GetCouponResp        = pb.GetCouponResp
	Items                = pb.Items
	ListCouponUsagesReq  = pb.ListCouponUsagesReq
	ListCouponUsagesResp = pb.ListCouponUsagesResp
	ListCouponsReq       = pb.ListCouponsReq
	ListCouponsResp      = pb.ListCouponsResp
	ListUserCouponsReq   = pb.ListUserCouponsReq
	ListUserCouponsResp  = pb.ListUserCouponsResp
	LockCouponReq        = pb.LockCouponReq
	PaginationReq        = pb.PaginationReq
	ReleaseCouponReq     = pb.ReleaseCouponReq
	UseCouponReq         = pb.UseCouponReq
	UserCoupon           = pb.UserCoupon

	Coupons interface {
		// ListCoupons 获取优惠券列表
		ListCoupons(ctx context.Context, in *ListCouponsReq, opts ...grpc.CallOption) (*ListCouponsResp, error)
		// GetCoupon 获取单个优惠券
		GetCoupon(ctx context.Context, in *GetCouponReq, opts ...grpc.CallOption) (*GetCouponResp, error)
		// ClaimCoupon 用户领取优惠券
		ClaimCoupon(ctx context.Context, in *ClaimCouponReq, opts ...grpc.CallOption) (*ClaimCouponResp, error)
		// ListUserCoupons 获取用户优惠券列表
		ListUserCoupons(ctx context.Context, in *ListUserCouponsReq, opts ...grpc.CallOption) (*ListUserCouponsResp, error)
		// CalculateCoupon 计算优惠券
		CalculateCoupon(ctx context.Context, in *CalculateCouponReq, opts ...grpc.CallOption) (*CalculateCouponResp, error)
		// CalculateCouponByItems 计算优惠券通过商品列表。
		ListCouponUsages(ctx context.Context, in *ListCouponUsagesReq, opts ...grpc.CallOption) (*ListCouponUsagesResp, error)
		// --------------- 使用优惠券 --------------- pre_order_id来进行使用
		LockCoupon(ctx context.Context, in *LockCouponReq, opts ...grpc.CallOption) (*EmptyResp, error)
		// 释放优惠券（订单取消/超时释放）
		ReleaseCoupon(ctx context.Context, in *ReleaseCouponReq, opts ...grpc.CallOption) (*EmptyResp, error)
		// 使用优惠券（支付成功确认后）
		UseCoupon(ctx context.Context, in *UseCouponReq, opts ...grpc.CallOption) (*EmptyResp, error)
	}

	defaultCoupons struct {
		cli zrpc.Client
	}
)

func NewCoupons(cli zrpc.Client) Coupons {
	return &defaultCoupons{
		cli: cli,
	}
}

// ListCoupons 获取优惠券列表
func (m *defaultCoupons) ListCoupons(ctx context.Context, in *ListCouponsReq, opts ...grpc.CallOption) (*ListCouponsResp, error) {
	client := pb.NewCouponsClient(m.cli.Conn())
	return client.ListCoupons(ctx, in, opts...)
}

// GetCoupon 获取单个优惠券
func (m *defaultCoupons) GetCoupon(ctx context.Context, in *GetCouponReq, opts ...grpc.CallOption) (*GetCouponResp, error) {
	client := pb.NewCouponsClient(m.cli.Conn())
	return client.GetCoupon(ctx, in, opts...)
}

// ClaimCoupon 用户领取优惠券
func (m *defaultCoupons) ClaimCoupon(ctx context.Context, in *ClaimCouponReq, opts ...grpc.CallOption) (*ClaimCouponResp, error) {
	client := pb.NewCouponsClient(m.cli.Conn())
	return client.ClaimCoupon(ctx, in, opts...)
}

// ListUserCoupons 获取用户优惠券列表
func (m *defaultCoupons) ListUserCoupons(ctx context.Context, in *ListUserCouponsReq, opts ...grpc.CallOption) (*ListUserCouponsResp, error) {
	client := pb.NewCouponsClient(m.cli.Conn())
	return client.ListUserCoupons(ctx, in, opts...)
}

// CalculateCoupon 计算优惠券
func (m *defaultCoupons) CalculateCoupon(ctx context.Context, in *CalculateCouponReq, opts ...grpc.CallOption) (*CalculateCouponResp, error) {
	client := pb.NewCouponsClient(m.cli.Conn())
	return client.CalculateCoupon(ctx, in, opts...)
}

// CalculateCouponByItems 计算优惠券通过商品列表。
func (m *defaultCoupons) ListCouponUsages(ctx context.Context, in *ListCouponUsagesReq, opts ...grpc.CallOption) (*ListCouponUsagesResp, error) {
	client := pb.NewCouponsClient(m.cli.Conn())
	return client.ListCouponUsages(ctx, in, opts...)
}

// --------------- 使用优惠券 --------------- pre_order_id来进行使用
func (m *defaultCoupons) LockCoupon(ctx context.Context, in *LockCouponReq, opts ...grpc.CallOption) (*EmptyResp, error) {
	client := pb.NewCouponsClient(m.cli.Conn())
	return client.LockCoupon(ctx, in, opts...)
}

// 释放优惠券（订单取消/超时释放）
func (m *defaultCoupons) ReleaseCoupon(ctx context.Context, in *ReleaseCouponReq, opts ...grpc.CallOption) (*EmptyResp, error) {
	client := pb.NewCouponsClient(m.cli.Conn())
	return client.ReleaseCoupon(ctx, in, opts...)
}

// 使用优惠券（支付成功确认后）
func (m *defaultCoupons) UseCoupon(ctx context.Context, in *UseCouponReq, opts ...grpc.CallOption) (*EmptyResp, error) {
	client := pb.NewCouponsClient(m.cli.Conn())
	return client.UseCoupon(ctx, in, opts...)
}
