// Code generated by goctl. DO NOT EDIT.
// Source: payment.proto

package paymentclient

import (
	"context"

	"github.com/falconfan123/Go-mall/services/payment/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	PaymentItem               = pb.PaymentItem
	PaymentListReq            = pb.PaymentListReq
	PaymentListReq_Pagination = pb.PaymentListReq_Pagination
	PaymentListResp           = pb.PaymentListResp
	PaymentReq                = pb.PaymentReq
	PaymentResp               = pb.PaymentResp

	Payment interface {
		CreatePayment(ctx context.Context, in *PaymentReq, opts ...grpc.CallOption) (*PaymentResp, error)
		ListPayments(ctx context.Context, in *PaymentListReq, opts ...grpc.CallOption) (*PaymentListResp, error)
	}

	defaultPayment struct {
		cli zrpc.Client
	}
)

func NewPayment(cli zrpc.Client) Payment {
	return &defaultPayment{
		cli: cli,
	}
}

func (m *defaultPayment) CreatePayment(ctx context.Context, in *PaymentReq, opts ...grpc.CallOption) (*PaymentResp, error) {
	client := pb.NewPaymentClient(m.cli.Conn())
	return client.CreatePayment(ctx, in, opts...)
}

func (m *defaultPayment) ListPayments(ctx context.Context, in *PaymentListReq, opts ...grpc.CallOption) (*PaymentListResp, error) {
	client := pb.NewPaymentClient(m.cli.Conn())
	return client.ListPayments(ctx, in, opts...)
}
