// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.1
// Source: order.proto

package orderservice

import (
	"context"

	"github.com/falconfan123/Go-mall/services/order/order"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CreateOrderRequest  = order.CreateOrderRequest
	CreateOrderResponse = order.CreateOrderResponse
	PaymentMethod       = order.PaymentMethod

	OrderService interface {
		CreateOrder(ctx context.Context, in *CreateOrderRequest, opts ...grpc.CallOption) (*CreateOrderResponse, error)
	}

	defaultOrderService struct {
		cli zrpc.Client
	}
)

func NewOrderService(cli zrpc.Client) OrderService {
	return &defaultOrderService{
		cli: cli,
	}
}

func (m *defaultOrderService) CreateOrder(ctx context.Context, in *CreateOrderRequest, opts ...grpc.CallOption) (*CreateOrderResponse, error) {
	client := order.NewOrderServiceClient(m.cli.Conn())
	return client.CreateOrder(ctx, in, opts...)
}
