// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: auths.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuthReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	ClientIp      string                 `protobuf:"bytes,2,opt,name=client_ip,json=clientIp,proto3" json:"client_ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthReq) Reset() {
	*x = AuthReq{}
	mi := &file_auths_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthReq) ProtoMessage() {}

func (x *AuthReq) ProtoReflect() protoreflect.Message {
	mi := &file_auths_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthReq.ProtoReflect.Descriptor instead.
func (*AuthReq) Descriptor() ([]byte, []int) {
	return file_auths_proto_rawDescGZIP(), []int{0}
}

func (x *AuthReq) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *AuthReq) GetClientIp() string {
	if x != nil {
		return x.ClientIp
	}
	return ""
}

type AuthGenReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	ClientIp      string                 `protobuf:"bytes,3,opt,name=client_ip,json=clientIp,proto3" json:"client_ip,omitempty"`
	DeviceId      string                 `protobuf:"bytes,4,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthGenReq) Reset() {
	*x = AuthGenReq{}
	mi := &file_auths_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthGenReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthGenReq) ProtoMessage() {}

func (x *AuthGenReq) ProtoReflect() protoreflect.Message {
	mi := &file_auths_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthGenReq.ProtoReflect.Descriptor instead.
func (*AuthGenReq) Descriptor() ([]byte, []int) {
	return file_auths_proto_rawDescGZIP(), []int{1}
}

func (x *AuthGenReq) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AuthGenReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *AuthGenReq) GetClientIp() string {
	if x != nil {
		return x.ClientIp
	}
	return ""
}

func (x *AuthGenReq) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

type AuthRenewalReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LongToken     string                 `protobuf:"bytes,1,opt,name=long_token,json=longToken,proto3" json:"long_token,omitempty"`    // 用户长令牌
	ShortToken    string                 `protobuf:"bytes,2,opt,name=short_token,json=shortToken,proto3" json:"short_token,omitempty"` // 用户短令牌（用于验证设备）
	ClientIp      string                 `protobuf:"bytes,3,opt,name=client_ip,json=clientIp,proto3" json:"client_ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthRenewalReq) Reset() {
	*x = AuthRenewalReq{}
	mi := &file_auths_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthRenewalReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthRenewalReq) ProtoMessage() {}

func (x *AuthRenewalReq) ProtoReflect() protoreflect.Message {
	mi := &file_auths_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthRenewalReq.ProtoReflect.Descriptor instead.
func (*AuthRenewalReq) Descriptor() ([]byte, []int) {
	return file_auths_proto_rawDescGZIP(), []int{2}
}

func (x *AuthRenewalReq) GetLongToken() string {
	if x != nil {
		return x.LongToken
	}
	return ""
}

func (x *AuthRenewalReq) GetShortToken() string {
	if x != nil {
		return x.ShortToken
	}
	return ""
}

func (x *AuthRenewalReq) GetClientIp() string {
	if x != nil {
		return x.ClientIp
	}
	return ""
}

type AuthsRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    uint32                 `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	StatusMsg     string                 `protobuf:"bytes,2,opt,name=status_msg,json=statusMsg,proto3" json:"status_msg,omitempty"`
	UserId        uint32                 `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // 用户id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthsRes) Reset() {
	*x = AuthsRes{}
	mi := &file_auths_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthsRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthsRes) ProtoMessage() {}

func (x *AuthsRes) ProtoReflect() protoreflect.Message {
	mi := &file_auths_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthsRes.ProtoReflect.Descriptor instead.
func (*AuthsRes) Descriptor() ([]byte, []int) {
	return file_auths_proto_rawDescGZIP(), []int{3}
}

func (x *AuthsRes) GetStatusCode() uint32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *AuthsRes) GetStatusMsg() string {
	if x != nil {
		return x.StatusMsg
	}
	return ""
}

func (x *AuthsRes) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type AuthGenRes struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	StatusCode     uint32                 `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	StatusMsg      string                 `protobuf:"bytes,2,opt,name=status_msg,json=statusMsg,proto3" json:"status_msg,omitempty"`
	ShortToken     string                 `protobuf:"bytes,3,opt,name=short_token,json=shortToken,proto3" json:"short_token,omitempty"`                // 短令牌（1天有效期）
	LongToken      string                 `protobuf:"bytes,4,opt,name=long_token,json=longToken,proto3" json:"long_token,omitempty"`                   // 长令牌（30天有效期）
	ShortExpiresIn int64                  `protobuf:"varint,5,opt,name=short_expires_in,json=shortExpiresIn,proto3" json:"short_expires_in,omitempty"` // 短令牌过期时间戳
	LongExpiresIn  int64                  `protobuf:"varint,6,opt,name=long_expires_in,json=longExpiresIn,proto3" json:"long_expires_in,omitempty"`    // 长令牌过期时间戳
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AuthGenRes) Reset() {
	*x = AuthGenRes{}
	mi := &file_auths_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthGenRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthGenRes) ProtoMessage() {}

func (x *AuthGenRes) ProtoReflect() protoreflect.Message {
	mi := &file_auths_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthGenRes.ProtoReflect.Descriptor instead.
func (*AuthGenRes) Descriptor() ([]byte, []int) {
	return file_auths_proto_rawDescGZIP(), []int{4}
}

func (x *AuthGenRes) GetStatusCode() uint32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *AuthGenRes) GetStatusMsg() string {
	if x != nil {
		return x.StatusMsg
	}
	return ""
}

func (x *AuthGenRes) GetShortToken() string {
	if x != nil {
		return x.ShortToken
	}
	return ""
}

func (x *AuthGenRes) GetLongToken() string {
	if x != nil {
		return x.LongToken
	}
	return ""
}

func (x *AuthGenRes) GetShortExpiresIn() int64 {
	if x != nil {
		return x.ShortExpiresIn
	}
	return 0
}

func (x *AuthGenRes) GetLongExpiresIn() int64 {
	if x != nil {
		return x.LongExpiresIn
	}
	return 0
}

type AuthRenewalRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    uint32                 `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"` // 状态码，0-成功，其他值-失败
	StatusMsg     string                 `protobuf:"bytes,2,opt,name=status_msg,json=statusMsg,proto3" json:"status_msg,omitempty"`     // 返回状态描述
	ShortToken    string                 `protobuf:"bytes,3,opt,name=short_token,json=shortToken,proto3" json:"short_token,omitempty"`  // 新的短令牌
	ExpiresIn     int64                  `protobuf:"varint,4,opt,name=expires_in,json=expiresIn,proto3" json:"expires_in,omitempty"`    // 短令牌过期时间戳
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthRenewalRes) Reset() {
	*x = AuthRenewalRes{}
	mi := &file_auths_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthRenewalRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthRenewalRes) ProtoMessage() {}

func (x *AuthRenewalRes) ProtoReflect() protoreflect.Message {
	mi := &file_auths_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthRenewalRes.ProtoReflect.Descriptor instead.
func (*AuthRenewalRes) Descriptor() ([]byte, []int) {
	return file_auths_proto_rawDescGZIP(), []int{5}
}

func (x *AuthRenewalRes) GetStatusCode() uint32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *AuthRenewalRes) GetStatusMsg() string {
	if x != nil {
		return x.StatusMsg
	}
	return ""
}

func (x *AuthRenewalRes) GetShortToken() string {
	if x != nil {
		return x.ShortToken
	}
	return ""
}

func (x *AuthRenewalRes) GetExpiresIn() int64 {
	if x != nil {
		return x.ExpiresIn
	}
	return 0
}

// 用于网关验证的请求
type AuthValidateReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"` // 令牌（短令牌或长令牌）
	ClientIp      string                 `protobuf:"bytes,2,opt,name=client_ip,json=clientIp,proto3" json:"client_ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthValidateReq) Reset() {
	*x = AuthValidateReq{}
	mi := &file_auths_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthValidateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthValidateReq) ProtoMessage() {}

func (x *AuthValidateReq) ProtoReflect() protoreflect.Message {
	mi := &file_auths_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthValidateReq.ProtoReflect.Descriptor instead.
func (*AuthValidateReq) Descriptor() ([]byte, []int) {
	return file_auths_proto_rawDescGZIP(), []int{6}
}

func (x *AuthValidateReq) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *AuthValidateReq) GetClientIp() string {
	if x != nil {
		return x.ClientIp
	}
	return ""
}

// 用于网关验证的响应
type AuthValidateRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    uint32                 `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	StatusMsg     string                 `protobuf:"bytes,2,opt,name=status_msg,json=statusMsg,proto3" json:"status_msg,omitempty"`
	UserId        uint32                 `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthValidateRes) Reset() {
	*x = AuthValidateRes{}
	mi := &file_auths_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthValidateRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthValidateRes) ProtoMessage() {}

func (x *AuthValidateRes) ProtoReflect() protoreflect.Message {
	mi := &file_auths_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthValidateRes.ProtoReflect.Descriptor instead.
func (*AuthValidateRes) Descriptor() ([]byte, []int) {
	return file_auths_proto_rawDescGZIP(), []int{7}
}

func (x *AuthValidateRes) GetStatusCode() uint32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *AuthValidateRes) GetStatusMsg() string {
	if x != nil {
		return x.StatusMsg
	}
	return ""
}

func (x *AuthValidateRes) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

// 用于登出的请求
type LogoutReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LongToken     string                 `protobuf:"bytes,1,opt,name=long_token,json=longToken,proto3" json:"long_token,omitempty"` // 长令牌
	ClientIp      string                 `protobuf:"bytes,2,opt,name=client_ip,json=clientIp,proto3" json:"client_ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutReq) Reset() {
	*x = LogoutReq{}
	mi := &file_auths_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutReq) ProtoMessage() {}

func (x *LogoutReq) ProtoReflect() protoreflect.Message {
	mi := &file_auths_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutReq.ProtoReflect.Descriptor instead.
func (*LogoutReq) Descriptor() ([]byte, []int) {
	return file_auths_proto_rawDescGZIP(), []int{8}
}

func (x *LogoutReq) GetLongToken() string {
	if x != nil {
		return x.LongToken
	}
	return ""
}

func (x *LogoutReq) GetClientIp() string {
	if x != nil {
		return x.ClientIp
	}
	return ""
}

// 用于登出的响应
type LogoutRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    uint32                 `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	StatusMsg     string                 `protobuf:"bytes,2,opt,name=status_msg,json=statusMsg,proto3" json:"status_msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutRes) Reset() {
	*x = LogoutRes{}
	mi := &file_auths_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutRes) ProtoMessage() {}

func (x *LogoutRes) ProtoReflect() protoreflect.Message {
	mi := &file_auths_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutRes.ProtoReflect.Descriptor instead.
func (*LogoutRes) Descriptor() ([]byte, []int) {
	return file_auths_proto_rawDescGZIP(), []int{9}
}

func (x *LogoutRes) GetStatusCode() uint32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *LogoutRes) GetStatusMsg() string {
	if x != nil {
		return x.StatusMsg
	}
	return ""
}

var File_auths_proto protoreflect.FileDescriptor

const file_auths_proto_rawDesc = "" +
	"\n" +
	"\vauths.proto\x12\x05auths\"<\n" +
	"\aAuthReq\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x1b\n" +
	"\tclient_ip\x18\x02 \x01(\tR\bclientIp\"{\n" +
	"\n" +
	"AuthGenReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1b\n" +
	"\tclient_ip\x18\x03 \x01(\tR\bclientIp\x12\x1b\n" +
	"\tdevice_id\x18\x04 \x01(\tR\bdeviceId\"m\n" +
	"\x0eAuthRenewalReq\x12\x1d\n" +
	"\n" +
	"long_token\x18\x01 \x01(\tR\tlongToken\x12\x1f\n" +
	"\vshort_token\x18\x02 \x01(\tR\n" +
	"shortToken\x12\x1b\n" +
	"\tclient_ip\x18\x03 \x01(\tR\bclientIp\"c\n" +
	"\bAuthsRes\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\rR\n" +
	"statusCode\x12\x1d\n" +
	"\n" +
	"status_msg\x18\x02 \x01(\tR\tstatusMsg\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\rR\x06userId\"\xde\x01\n" +
	"\n" +
	"AuthGenRes\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\rR\n" +
	"statusCode\x12\x1d\n" +
	"\n" +
	"status_msg\x18\x02 \x01(\tR\tstatusMsg\x12\x1f\n" +
	"\vshort_token\x18\x03 \x01(\tR\n" +
	"shortToken\x12\x1d\n" +
	"\n" +
	"long_token\x18\x04 \x01(\tR\tlongToken\x12(\n" +
	"\x10short_expires_in\x18\x05 \x01(\x03R\x0eshortExpiresIn\x12&\n" +
	"\x0flong_expires_in\x18\x06 \x01(\x03R\rlongExpiresIn\"\x90\x01\n" +
	"\x0eAuthRenewalRes\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\rR\n" +
	"statusCode\x12\x1d\n" +
	"\n" +
	"status_msg\x18\x02 \x01(\tR\tstatusMsg\x12\x1f\n" +
	"\vshort_token\x18\x03 \x01(\tR\n" +
	"shortToken\x12\x1d\n" +
	"\n" +
	"expires_in\x18\x04 \x01(\x03R\texpiresIn\"D\n" +
	"\x0fAuthValidateReq\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x1b\n" +
	"\tclient_ip\x18\x02 \x01(\tR\bclientIp\"j\n" +
	"\x0fAuthValidateRes\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\rR\n" +
	"statusCode\x12\x1d\n" +
	"\n" +
	"status_msg\x18\x02 \x01(\tR\tstatusMsg\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\rR\x06userId\"G\n" +
	"\tLogoutReq\x12\x1d\n" +
	"\n" +
	"long_token\x18\x01 \x01(\tR\tlongToken\x12\x1b\n" +
	"\tclient_ip\x18\x02 \x01(\tR\bclientIp\"K\n" +
	"\tLogoutRes\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\rR\n" +
	"statusCode\x12\x1d\n" +
	"\n" +
	"status_msg\x18\x02 \x01(\tR\tstatusMsg2\x9c\x02\n" +
	"\x05Auths\x121\n" +
	"\x0eAuthentication\x12\x0e.auths.AuthReq\x1a\x0f.auths.AuthsRes\x125\n" +
	"\rGenerateToken\x12\x11.auths.AuthGenReq\x1a\x11.auths.AuthGenRes\x12:\n" +
	"\n" +
	"RenewToken\x12\x15.auths.AuthRenewalReq\x1a\x15.auths.AuthRenewalRes\x12?\n" +
	"\rValidateToken\x12\x16.auths.AuthValidateReq\x1a\x16.auths.AuthValidateRes\x12,\n" +
	"\x06Logout\x12\x10.auths.LogoutReq\x1a\x10.auths.LogoutResB\tZ\a./authsb\x06proto3"

var (
	file_auths_proto_rawDescOnce sync.Once
	file_auths_proto_rawDescData []byte
)

func file_auths_proto_rawDescGZIP() []byte {
	file_auths_proto_rawDescOnce.Do(func() {
		file_auths_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_auths_proto_rawDesc), len(file_auths_proto_rawDesc)))
	})
	return file_auths_proto_rawDescData
}

var file_auths_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_auths_proto_goTypes = []any{
	(*AuthReq)(nil),         // 0: auths.AuthReq
	(*AuthGenReq)(nil),      // 1: auths.AuthGenReq
	(*AuthRenewalReq)(nil),  // 2: auths.AuthRenewalReq
	(*AuthsRes)(nil),        // 3: auths.AuthsRes
	(*AuthGenRes)(nil),      // 4: auths.AuthGenRes
	(*AuthRenewalRes)(nil),  // 5: auths.AuthRenewalRes
	(*AuthValidateReq)(nil), // 6: auths.AuthValidateReq
	(*AuthValidateRes)(nil), // 7: auths.AuthValidateRes
	(*LogoutReq)(nil),       // 8: auths.LogoutReq
	(*LogoutRes)(nil),       // 9: auths.LogoutRes
}
var file_auths_proto_depIdxs = []int32{
	0, // 0: auths.Auths.Authentication:input_type -> auths.AuthReq
	1, // 1: auths.Auths.GenerateToken:input_type -> auths.AuthGenReq
	2, // 2: auths.Auths.RenewToken:input_type -> auths.AuthRenewalReq
	6, // 3: auths.Auths.ValidateToken:input_type -> auths.AuthValidateReq
	8, // 4: auths.Auths.Logout:input_type -> auths.LogoutReq
	3, // 5: auths.Auths.Authentication:output_type -> auths.AuthsRes
	4, // 6: auths.Auths.GenerateToken:output_type -> auths.AuthGenRes
	5, // 7: auths.Auths.RenewToken:output_type -> auths.AuthRenewalRes
	7, // 8: auths.Auths.ValidateToken:output_type -> auths.AuthValidateRes
	9, // 9: auths.Auths.Logout:output_type -> auths.LogoutRes
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_auths_proto_init() }
func file_auths_proto_init() {
	if File_auths_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auths_proto_rawDesc), len(file_auths_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_auths_proto_goTypes,
		DependencyIndexes: file_auths_proto_depIdxs,
		MessageInfos:      file_auths_proto_msgTypes,
	}.Build()
	File_auths_proto = out.File
	file_auths_proto_goTypes = nil
	file_auths_proto_depIdxs = nil
}
