// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: search.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ParseQueryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParseQueryRequest) Reset() {
	*x = ParseQueryRequest{}
	mi := &file_search_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParseQueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseQueryRequest) ProtoMessage() {}

func (x *ParseQueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_search_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseQueryRequest.ProtoReflect.Descriptor instead.
func (*ParseQueryRequest) Descriptor() ([]byte, []int) {
	return file_search_proto_rawDescGZIP(), []int{0}
}

func (x *ParseQueryRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

type ParseQueryResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	OriginalQuery     string                 `protobuf:"bytes,1,opt,name=original_query,json=originalQuery,proto3" json:"original_query,omitempty"`
	NormalizedQuery   string                 `protobuf:"bytes,2,opt,name=normalized_query,json=normalizedQuery,proto3" json:"normalized_query,omitempty"`
	PredictedCategory string                 `protobuf:"bytes,3,opt,name=predicted_category,json=predictedCategory,proto3" json:"predicted_category,omitempty"`
	Brands            []string               `protobuf:"bytes,4,rep,name=brands,proto3" json:"brands,omitempty"`
	ProductWords      []string               `protobuf:"bytes,5,rep,name=product_words,json=productWords,proto3" json:"product_words,omitempty"`
	Modifiers         []string               `protobuf:"bytes,6,rep,name=modifiers,proto3" json:"modifiers,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ParseQueryResponse) Reset() {
	*x = ParseQueryResponse{}
	mi := &file_search_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParseQueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseQueryResponse) ProtoMessage() {}

func (x *ParseQueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_search_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseQueryResponse.ProtoReflect.Descriptor instead.
func (*ParseQueryResponse) Descriptor() ([]byte, []int) {
	return file_search_proto_rawDescGZIP(), []int{1}
}

func (x *ParseQueryResponse) GetOriginalQuery() string {
	if x != nil {
		return x.OriginalQuery
	}
	return ""
}

func (x *ParseQueryResponse) GetNormalizedQuery() string {
	if x != nil {
		return x.NormalizedQuery
	}
	return ""
}

func (x *ParseQueryResponse) GetPredictedCategory() string {
	if x != nil {
		return x.PredictedCategory
	}
	return ""
}

func (x *ParseQueryResponse) GetBrands() []string {
	if x != nil {
		return x.Brands
	}
	return nil
}

func (x *ParseQueryResponse) GetProductWords() []string {
	if x != nil {
		return x.ProductWords
	}
	return nil
}

func (x *ParseQueryResponse) GetModifiers() []string {
	if x != nil {
		return x.Modifiers
	}
	return nil
}

type SearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Category      string                 `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	SortBy        string                 `protobuf:"bytes,5,opt,name=sort_by,json=sortBy,proto3" json:"sort_by,omitempty"`
	SortOrder     string                 `protobuf:"bytes,6,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_search_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_search_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_search_proto_rawDescGZIP(), []int{2}
}

func (x *SearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *SearchRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *SearchRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *SearchRequest) GetSortBy() string {
	if x != nil {
		return x.SortBy
	}
	return ""
}

func (x *SearchRequest) GetSortOrder() string {
	if x != nil {
		return x.SortOrder
	}
	return ""
}

type SearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*SearchResult        `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	TotalPages    int32                  `protobuf:"varint,5,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_search_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_search_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_search_proto_rawDescGZIP(), []int{3}
}

func (x *SearchResponse) GetResults() []*SearchResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *SearchResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *SearchResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *SearchResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *SearchResponse) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

type SearchResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Price         float64                `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,5,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	Category      string                 `protobuf:"bytes,6,opt,name=category,proto3" json:"category,omitempty"`
	Brand         string                 `protobuf:"bytes,7,opt,name=brand,proto3" json:"brand,omitempty"`
	Score         float64                `protobuf:"fixed64,8,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResult) Reset() {
	*x = SearchResult{}
	mi := &file_search_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResult) ProtoMessage() {}

func (x *SearchResult) ProtoReflect() protoreflect.Message {
	mi := &file_search_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResult.ProtoReflect.Descriptor instead.
func (*SearchResult) Descriptor() ([]byte, []int) {
	return file_search_proto_rawDescGZIP(), []int{4}
}

func (x *SearchResult) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SearchResult) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SearchResult) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *SearchResult) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *SearchResult) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *SearchResult) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *SearchResult) GetBrand() string {
	if x != nil {
		return x.Brand
	}
	return ""
}

func (x *SearchResult) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

var File_search_proto protoreflect.FileDescriptor

const file_search_proto_rawDesc = "" +
	"\n" +
	"\fsearch.proto\x12\x06search\")\n" +
	"\x11ParseQueryRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\"\xf0\x01\n" +
	"\x12ParseQueryResponse\x12%\n" +
	"\x0eoriginal_query\x18\x01 \x01(\tR\roriginalQuery\x12)\n" +
	"\x10normalized_query\x18\x02 \x01(\tR\x0fnormalizedQuery\x12-\n" +
	"\x12predicted_category\x18\x03 \x01(\tR\x11predictedCategory\x12\x16\n" +
	"\x06brands\x18\x04 \x03(\tR\x06brands\x12#\n" +
	"\rproduct_words\x18\x05 \x03(\tR\fproductWords\x12\x1c\n" +
	"\tmodifiers\x18\x06 \x03(\tR\tmodifiers\"\xaa\x01\n" +
	"\rSearchRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x1a\n" +
	"\bcategory\x18\x02 \x01(\tR\bcategory\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\x12\x17\n" +
	"\asort_by\x18\x05 \x01(\tR\x06sortBy\x12\x1d\n" +
	"\n" +
	"sort_order\x18\x06 \x01(\tR\tsortOrder\"\xa8\x01\n" +
	"\x0eSearchResponse\x12.\n" +
	"\aresults\x18\x01 \x03(\v2\x14.search.SearchResultR\aresults\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\x12\x1f\n" +
	"\vtotal_pages\x18\x05 \x01(\x05R\n" +
	"totalPages\"\xcf\x01\n" +
	"\fSearchResult\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x01R\x05price\x12\x1b\n" +
	"\timage_url\x18\x05 \x01(\tR\bimageUrl\x12\x1a\n" +
	"\bcategory\x18\x06 \x01(\tR\bcategory\x12\x14\n" +
	"\x05brand\x18\a \x01(\tR\x05brand\x12\x14\n" +
	"\x05score\x18\b \x01(\x01R\x05score2\x8d\x01\n" +
	"\rSearchService\x12C\n" +
	"\n" +
	"ParseQuery\x12\x19.search.ParseQueryRequest\x1a\x1a.search.ParseQueryResponse\x127\n" +
	"\x06Search\x12\x15.search.SearchRequest\x1a\x16.search.SearchResponseB4Z2github.com/falconfan123/Go-mall/services/search/pbb\x06proto3"

var (
	file_search_proto_rawDescOnce sync.Once
	file_search_proto_rawDescData []byte
)

func file_search_proto_rawDescGZIP() []byte {
	file_search_proto_rawDescOnce.Do(func() {
		file_search_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_search_proto_rawDesc), len(file_search_proto_rawDesc)))
	})
	return file_search_proto_rawDescData
}

var file_search_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_search_proto_goTypes = []any{
	(*ParseQueryRequest)(nil),  // 0: search.ParseQueryRequest
	(*ParseQueryResponse)(nil), // 1: search.ParseQueryResponse
	(*SearchRequest)(nil),      // 2: search.SearchRequest
	(*SearchResponse)(nil),     // 3: search.SearchResponse
	(*SearchResult)(nil),       // 4: search.SearchResult
}
var file_search_proto_depIdxs = []int32{
	4, // 0: search.SearchResponse.results:type_name -> search.SearchResult
	0, // 1: search.SearchService.ParseQuery:input_type -> search.ParseQueryRequest
	2, // 2: search.SearchService.Search:input_type -> search.SearchRequest
	1, // 3: search.SearchService.ParseQuery:output_type -> search.ParseQueryResponse
	3, // 4: search.SearchService.Search:output_type -> search.SearchResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_search_proto_init() }
func file_search_proto_init() {
	if File_search_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_search_proto_rawDesc), len(file_search_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_search_proto_goTypes,
		DependencyIndexes: file_search_proto_depIdxs,
		MessageInfos:      file_search_proto_msgTypes,
	}.Build()
	File_search_proto = out.File
	file_search_proto_goTypes = nil
	file_search_proto_depIdxs = nil
}
