// Code generated by MockGen. DO NOT EDIT.
// Source: /Users/fan/.superset/projects/Go-mall/services/inventory/internal/domain/repository/inventory_repository.go
//
// Generated by this command:
//
//	mockgen -source /Users/fan/.superset/projects/Go-mall/services/inventory/internal/domain/repository/inventory_repository.go -package testmock -destination /Users/fan/.superset/projects/Go-mall/services/inventory/internal/testmock/mock_inventory_repository.go
//

// Package testmock is a generated GoMock package.
package testmock

import (
	context "context"
	reflect "reflect"

	aggregate "github.com/falconfan123/Go-mall/services/inventory/internal/domain/aggregate"
	gomock "go.uber.org/mock/gomock"
)

// MockInventoryRepository is a mock of InventoryRepository interface.
type MockInventoryRepository struct {
	ctrl     *gomock.Controller
	recorder *MockInventoryRepositoryMockRecorder
	isgomock struct{}
}

// MockInventoryRepositoryMockRecorder is the mock recorder for MockInventoryRepository.
type MockInventoryRepositoryMockRecorder struct {
	mock *MockInventoryRepository
}

// NewMockInventoryRepository creates a new mock instance.
func NewMockInventoryRepository(ctrl *gomock.Controller) *MockInventoryRepository {
	mock := &MockInventoryRepository{ctrl: ctrl}
	mock.recorder = &MockInventoryRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInventoryRepository) EXPECT() *MockInventoryRepositoryMockRecorder {
	return m.recorder
}

// BatchGetByProductIDs mocks base method.
func (m *MockInventoryRepository) BatchGetByProductIDs(ctx context.Context, productIDs []int64) ([]*aggregate.Inventory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchGetByProductIDs", ctx, productIDs)
	ret0, _ := ret[0].([]*aggregate.Inventory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BatchGetByProductIDs indicates an expected call of BatchGetByProductIDs.
func (mr *MockInventoryRepositoryMockRecorder) BatchGetByProductIDs(ctx, productIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchGetByProductIDs", reflect.TypeOf((*MockInventoryRepository)(nil).BatchGetByProductIDs), ctx, productIDs)
}

// DecreaseStock mocks base method.
func (m *MockInventoryRepository) DecreaseStock(ctx context.Context, productID, quantity int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DecreaseStock", ctx, productID, quantity)
	ret0, _ := ret[0].(error)
	return ret0
}

// DecreaseStock indicates an expected call of DecreaseStock.
func (mr *MockInventoryRepositoryMockRecorder) DecreaseStock(ctx, productID, quantity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DecreaseStock", reflect.TypeOf((*MockInventoryRepository)(nil).DecreaseStock), ctx, productID, quantity)
}

// GetByProductID mocks base method.
func (m *MockInventoryRepository) GetByProductID(ctx context.Context, productID int64) (*aggregate.Inventory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByProductID", ctx, productID)
	ret0, _ := ret[0].(*aggregate.Inventory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByProductID indicates an expected call of GetByProductID.
func (mr *MockInventoryRepositoryMockRecorder) GetByProductID(ctx, productID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByProductID", reflect.TypeOf((*MockInventoryRepository)(nil).GetByProductID), ctx, productID)
}

// GetPreInventoryRecord mocks base method.
func (m *MockInventoryRepository) GetPreInventoryRecord(ctx context.Context, preOrderID string, productID int64) (*aggregate.Inventory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPreInventoryRecord", ctx, preOrderID, productID)
	ret0, _ := ret[0].(*aggregate.Inventory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPreInventoryRecord indicates an expected call of GetPreInventoryRecord.
func (mr *MockInventoryRepositoryMockRecorder) GetPreInventoryRecord(ctx, preOrderID, productID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPreInventoryRecord", reflect.TypeOf((*MockInventoryRepository)(nil).GetPreInventoryRecord), ctx, preOrderID, productID)
}

// IncreaseStock mocks base method.
func (m *MockInventoryRepository) IncreaseStock(ctx context.Context, productID, quantity int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncreaseStock", ctx, productID, quantity)
	ret0, _ := ret[0].(error)
	return ret0
}

// IncreaseStock indicates an expected call of IncreaseStock.
func (mr *MockInventoryRepositoryMockRecorder) IncreaseStock(ctx, productID, quantity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncreaseStock", reflect.TypeOf((*MockInventoryRepository)(nil).IncreaseStock), ctx, productID, quantity)
}

// RemovePreInventoryRecord mocks base method.
func (m *MockInventoryRepository) RemovePreInventoryRecord(ctx context.Context, preOrderID string, productID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemovePreInventoryRecord", ctx, preOrderID, productID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemovePreInventoryRecord indicates an expected call of RemovePreInventoryRecord.
func (mr *MockInventoryRepositoryMockRecorder) RemovePreInventoryRecord(ctx, preOrderID, productID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemovePreInventoryRecord", reflect.TypeOf((*MockInventoryRepository)(nil).RemovePreInventoryRecord), ctx, preOrderID, productID)
}

// Save mocks base method.
func (m *MockInventoryRepository) Save(ctx context.Context, inventory *aggregate.Inventory) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, inventory)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockInventoryRepositoryMockRecorder) Save(ctx, inventory any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockInventoryRepository)(nil).Save), ctx, inventory)
}

// SavePreInventoryRecord mocks base method.
func (m *MockInventoryRepository) SavePreInventoryRecord(ctx context.Context, record *aggregate.Inventory) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SavePreInventoryRecord", ctx, record)
	ret0, _ := ret[0].(error)
	return ret0
}

// SavePreInventoryRecord indicates an expected call of SavePreInventoryRecord.
func (mr *MockInventoryRepositoryMockRecorder) SavePreInventoryRecord(ctx, record any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SavePreInventoryRecord", reflect.TypeOf((*MockInventoryRepository)(nil).SavePreInventoryRecord), ctx, record)
}
