// Code generated by MockGen. DO NOT EDIT.
// Source: /Users/fan/.superset/projects/Go-mall/services/inventory/internal/application/event/event_publisher.go
//
// Generated by this command:
//
//	mockgen -source /Users/fan/.superset/projects/Go-mall/services/inventory/internal/application/event/event_publisher.go -package testmock -destination /Users/fan/.superset/projects/Go-mall/services/inventory/internal/testmock/mock_event_publisher.go
//

// Package testmock is a generated GoMock package.
package testmock

import (
	reflect "reflect"

	event "github.com/falconfan123/Go-mall/services/inventory/internal/domain/event"
	gomock "go.uber.org/mock/gomock"
)

// MockInventoryEventPublisher is a mock of InventoryEventPublisher interface.
type MockInventoryEventPublisher struct {
	ctrl     *gomock.Controller
	recorder *MockInventoryEventPublisherMockRecorder
	isgomock struct{}
}

// MockInventoryEventPublisherMockRecorder is the mock recorder for MockInventoryEventPublisher.
type MockInventoryEventPublisherMockRecorder struct {
	mock *MockInventoryEventPublisher
}

// NewMockInventoryEventPublisher creates a new mock instance.
func NewMockInventoryEventPublisher(ctrl *gomock.Controller) *MockInventoryEventPublisher {
	mock := &MockInventoryEventPublisher{ctrl: ctrl}
	mock.recorder = &MockInventoryEventPublisherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInventoryEventPublisher) EXPECT() *MockInventoryEventPublisherMockRecorder {
	return m.recorder
}

// PublishInventoryDecreased mocks base method.
func (m *MockInventoryEventPublisher) PublishInventoryDecreased(evt *event.InventoryDecreasedEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishInventoryDecreased", evt)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishInventoryDecreased indicates an expected call of PublishInventoryDecreased.
func (mr *MockInventoryEventPublisherMockRecorder) PublishInventoryDecreased(evt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishInventoryDecreased", reflect.TypeOf((*MockInventoryEventPublisher)(nil).PublishInventoryDecreased), evt)
}

// PublishInventoryPreDecreased mocks base method.
func (m *MockInventoryEventPublisher) PublishInventoryPreDecreased(evt *event.InventoryPreDecreasedEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishInventoryPreDecreased", evt)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishInventoryPreDecreased indicates an expected call of PublishInventoryPreDecreased.
func (mr *MockInventoryEventPublisherMockRecorder) PublishInventoryPreDecreased(evt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishInventoryPreDecreased", reflect.TypeOf((*MockInventoryEventPublisher)(nil).PublishInventoryPreDecreased), evt)
}

// PublishInventoryPreReturned mocks base method.
func (m *MockInventoryEventPublisher) PublishInventoryPreReturned(evt *event.InventoryPreReturnedEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishInventoryPreReturned", evt)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishInventoryPreReturned indicates an expected call of PublishInventoryPreReturned.
func (mr *MockInventoryEventPublisherMockRecorder) PublishInventoryPreReturned(evt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishInventoryPreReturned", reflect.TypeOf((*MockInventoryEventPublisher)(nil).PublishInventoryPreReturned), evt)
}

// PublishInventoryReturned mocks base method.
func (m *MockInventoryEventPublisher) PublishInventoryReturned(evt *event.InventoryReturnedEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishInventoryReturned", evt)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishInventoryReturned indicates an expected call of PublishInventoryReturned.
func (mr *MockInventoryEventPublisherMockRecorder) PublishInventoryReturned(evt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishInventoryReturned", reflect.TypeOf((*MockInventoryEventPublisher)(nil).PublishInventoryReturned), evt)
}

// PublishInventoryUpdated mocks base method.
func (m *MockInventoryEventPublisher) PublishInventoryUpdated(evt *event.InventoryUpdatedEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishInventoryUpdated", evt)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishInventoryUpdated indicates an expected call of PublishInventoryUpdated.
func (mr *MockInventoryEventPublisherMockRecorder) PublishInventoryUpdated(evt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishInventoryUpdated", reflect.TypeOf((*MockInventoryEventPublisher)(nil).PublishInventoryUpdated), evt)
}
