// Code generated by goctl. DO NOT EDIT.
package types

type GetFlashProductsReq struct {
	Page     int64 `json:"page,default=1"`  // 当前页码，默认为1
	PageSize int64 `json:"size,default=10"` // 每页大小，默认为10
}

type GetFlashProductsResp struct {
	Products []*FlashProduct `json:"products"` // 秒杀商品列表
	Total    int64           `json:"total"`    // 总记录数
	Page     int64           `json:"page"`     // 当前页码
	PageSize int64           `json:"pageSize"` // 每页大小
}

type FlashProduct struct {
	ID          int64  `json:"id"`          // 商品ID
	Name        string `json:"name"`        // 商品名称
	Description string `json:"description"` // 商品描述
	Picture     string `json:"picture"`     // 商品图片URL
	Price       int64  `json:"price"`       // 原价
	FlashPrice  int64  `json:"flashPrice"`  // 秒杀价
	Stock       int64  `json:"stock"`       // 秒杀库存
	Sold        int64  `json:"sold"`        // 已售数量
	CreatedAt   string `json:"createdAt"`
	UpdatedAt   string `json:"updatedAt"`
}

type FlashBuyReq struct {
	ProductID int64 `json:"productId" form:"product_id"` // 商品ID
	Quantity  int64 `json:"quantity" form:"quantity"`    // 购买数量
}

type FlashBuyResp struct {
	OrderID string `json:"orderId"` // 订单ID
	OrderNo string `json:"orderNo"` // 订单号
	Total   int64  `json:"total"`   // 订单总金额
}
